<script type="text/javascript">
    var id_departamento;
    var id_aula;
    $(document).ready(function() {



        /*******************************************************************/
        /* Validación formulario                                           */
        /*******************************************************************/
        var formvalidator = $("#formulario").validate({
            /*bug hacía el validate con la fecha "antigua", antes de la selección*/

            rules: {
                causa: {
                    required: true
                },
                fecha_incidencia: {
                    required: true
                },
                prioridad: {
                    required: true
                },
                id_usuario: {
                    required: true
                }
            },
            messages: {
                causa: {
                    required: "Debes rellenar la causa de la incidencia"
                }
            }
        });
        /*******************************************************************/
        /*Configuración datatables                                         */
        /*******************************************************************/
        $.extend($.fn.dataTableExt.oStdClasses, {
            "sWrapper": "dataTables_wrapper form-inline"
        });
        $.fn.dataTableExt.oApi.fnStandingRedraw = function(oSettings) {
            if (oSettings.oFeatures.bServerSide === false) {
                var before = oSettings._iDisplayStart;
                oSettings.oApi._fnReDraw(oSettings);
                // iDisplayStart has been reset to zero - so lets change it back
                oSettings._iDisplayStart = before;
                oSettings.oApi._fnCalculateEnd(oSettings);
            }
            // draw the 'current' page
            oSettings.oApi._fnDraw(oSettings);
        };
        /* API method to get paging information */
        $.fn.dataTableExt.oApi.fnPagingInfo = function(oSettings)
        {
            return {
                "iStart": oSettings._iDisplayStart,
                "iEnd": oSettings.fnDisplayEnd(),
                "iLength": oSettings._iDisplayLength,
                "iTotal": oSettings.fnRecordsTotal(),
                "iFilteredTotal": oSettings.fnRecordsDisplay(),
                "iPage": Math.ceil(oSettings._iDisplayStart / oSettings._iDisplayLength),
                "iTotalPages": Math.ceil(oSettings.fnRecordsDisplay() / oSettings._iDisplayLength)
            };
        };
        /* Bootstrap style pagination control */
        $.extend($.fn.dataTableExt.oPagination, {
            "bootstrap": {
                "fnInit": function(oSettings, nPaging, fnDraw) {
                    var oLang = oSettings.oLanguage.oPaginate;
                    var fnClickHandler = function(e) {
                        e.preventDefault();
                        if (oSettings.oApi._fnPageChange(oSettings, e.data.action)) {
                            fnDraw(oSettings);
                        }
                    };
                    $(nPaging).addClass('pagination').append(
                            '<ul>' +
                            '<li class="prev disabled"><a href="#">&larr; ' + oLang.sPrevious + '</a></li>' +
                            '<li class="next disabled"><a href="#">' + oLang.sNext + ' &rarr; </a></li>' +
                            '</ul>'
                            );
                    var els = $('a', nPaging);
                    $(els[0]).bind('click.DT', {action: "previous"}, fnClickHandler);
                    $(els[1]).bind('click.DT', {action: "next"}, fnClickHandler);
                },
                "fnUpdate": function(oSettings, fnDraw) {
                    var iListLength = 5;
                    var oPaging = oSettings.oInstance.fnPagingInfo();
                    var an = oSettings.aanFeatures.p;
                    var i, j, sClass, iStart, iEnd, iHalf = Math.floor(iListLength / 2);
                    if (oPaging.iTotalPages < iListLength) {
                        iStart = 1;
                        iEnd = oPaging.iTotalPages;
                    }
                    else if (oPaging.iPage <= iHalf) {
                        iStart = 1;
                        iEnd = iListLength;
                    } else if (oPaging.iPage >= (oPaging.iTotalPages - iHalf)) {
                        iStart = oPaging.iTotalPages - iListLength + 1;
                        iEnd = oPaging.iTotalPages;
                    } else {
                        iStart = oPaging.iPage - iHalf + 1;
                        iEnd = iStart + iListLength - 1;
                    }

                    for (i = 0, iLen = an.length; i < iLen; i++) {
                        // Remove the middle elements
                        $('li:gt(0)', an[i]).filter(':not(:last)').remove();
                        // Add the new list items and their event handlers
                        for (j = iStart; j <= iEnd; j++) {
                            sClass = (j == oPaging.iPage + 1) ? 'class="active"' : '';
                            $('<li ' + sClass + '><a href="#">' + j + '</a></li>')
                                    .insertBefore($('li:last', an[i])[0])
                                    .bind('click', function(e) {
                                        e.preventDefault();
                                        oSettings._iDisplayStart = (parseInt($('a', this).text(), 10) - 1) * oPaging.iLength;
                                        fnDraw(oSettings);
                                    });
                        }

                        // Add / remove disabled classes from the static elements
                        if (oPaging.iPage === 0) {
                            $('li:first', an[i]).addClass('disabled');
                        } else {
                            $('li:first', an[i]).removeClass('disabled');
                        }

                        if (oPaging.iPage === oPaging.iTotalPages - 1 || oPaging.iTotalPages === 0) {
                            $('li:last', an[i]).addClass('disabled');
                        } else {
                            $('li:last', an[i]).removeClass('disabled');
                        }
                    }
                }
            }
        });
        $.fn.dataTableExt.oApi.fnMultiFilter = function(oSettings, oData) {
            for (var key in oData)
            {
                if (oData.hasOwnProperty(key))
                {
                    for (var i = 0, iLen = oSettings.aoColumns.length; i < iLen; i++)
                    {
                        if (oSettings.aoColumns[i].sName == key)
                        {
                            /* Add single column filter */
                            oSettings.aoPreSearchCols[ i ].sSearch = oData[key];
                            break;
                        }
                    }
                }
            }
            this.oApi._fnReDraw(oSettings);
        };
        /******************************************************************/
        /* INICIALIZACIÓN DATATABLES: Configuración columnas y script php */
        /******************************************************************/
        oTable = $('#tabla').dataTable({
            "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span12'i><'span12 center'p>>",
            /*"<'row-fluid'<'span6'T><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",*/
            "fnServerParams": function(aoData) {
                aoData.push({"name": "estado", "value": 'En uso'});
                aoData.push({"name": "id_departamento", "value": id_departamento});
            },
            "sAjaxSource": "<?php echo $this->baseUrl("/php/inventario.php"); ?>",
            "bProcessing": true,
            "bServerSide": true,
            //si lo desmarcamos la cookie del listado de incidencias se trae también aquí y los filtros dan error
            //de cualquier manera, queda mejor así
            //"bStateSave": true,
            "bAutoWidth": false,
            "sPaginationType": "bootstrap",
            "fnInitComplete": function() {
                var oSettings = $('#tabla').dataTable().fnSettings();
                for (var i = 0; i < oSettings.aoPreSearchCols.length; i++) {
                    if (oSettings.aoPreSearchCols[i].sSearch.length > 0) {
                        $("thead input, thead select")[i].value = oSettings.aoPreSearchCols[i].sSearch;
                        // $("tfoot input")[i].className = "";
                    }
                }
            },
            "aoColumns": [
                {
                    "mData": "modelo",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "modelo"
                },
                {
                    "mData": "codigo",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "codigo"
                },
                {
                    "mData": "fecha_adquisicion",
                    "mRender": function(data, type, full) {
                        return fecha_ddmmyyyy(data);
                    },
                    "bSearchable": false,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "fecha_adquisicion"
                },
                {
                    "mData": "aula",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": false,
                    "sName": "aula"
                },
                {
                    "mData": "puesto",
                    "bSearchable": false,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "puesto"
                },
                {
                    "mData": "tipo",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "tipo"
                },
                {
                    "mData": "responsables",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "responsables"
                },
                {
                    "mData": "id_inventario",
                    "sClass": "center",
                    "mRender": function(data, type, full) {
                        return '<a title="Seleccionar material para nueva incidencia" style="margin:3px;" class="btn btn-info editarbtn" href="#"><i class="halflings-icon edit halflings-icon"></i></a><a title="Ver histórico de incidencias del material" style="margin:3px;" class="btn btn-success historialbtn" href="<?php echo $this->baseUrl('/inventario/historial/id_inventario/'); ?>' + data + '"><i class="halflings-icon search halflings-icon"></i></a>';
                    },
                    "bSortable": false,
                    "bSearchable": false
                },
                {
                    "mData": "id_inventario",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false

                },
                {
                    "mData": "aulas_id_aula",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                },
                {
                    "mData": "tipos_id_tipo",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                },
                {
                    "mData": "id_proveedor",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false

                },
                {
                    "mData": "estado",
                    "bSearchable": false,
                    "bVisible": false,
                    "mRender": function(data, type, full) {
                        if (data == "En uso") {
                            return '<span class="label label-success">En uso</span>';
                        }
                        else if (data == "Baja") {
                            return '<span class="label">Baja</span>';
                        }
                        else if (data == "Averiado") {
                            return '<span class="label label-important">Averiado</span>';
                        }
                    },
                    "bSortable": true
                },
                {
                    "mData": "obs",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false

                },
                {
                    "mData": "id_departamento",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                },
                {
                    "mData": "departamento",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                },
                {
                    "mData": "proveedor",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false,
                    "sName": "proveedor"
                }
            ],
            "aaSorting": [[0, "asc"]],
            "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
            "oLanguage": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros por página",
                "sZeroRecords": "No se encontraron resultados",
                "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                "sInfoFiltered": "(Filtrado de _MAX_ registros en total)",
                "sLoadingRecords": "Por favor espere - cargando...",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sPrevious": "Anterior",
                    "sNext": "Siguiente",
                    "sLast": "Último"
                }
            },
            "fnDrawCallback": function() {
                $('#tabla tbody td:not(.accion)').click(edicion);

                $('#tabla tbody tr').hover(function() {
                    $(this).css('cursor', 'pointer');
                }, function() {
                    $(this).css('cursor', 'auto');
                });
            }
        });
        $(".sborrar").click(function() {
            $(this).prev().val("");
            $("thead input").keyup();
        });
        $("thead input, thead select").on("click keyup", function() {
            vsmodelo = $("#smodelo").val();
            vscodigo = $("#scodigo").val();
            vsaula = $("#saula").val();
            vstipo = $("#stipo").val();
            vsresponsables = $("#sresponsables").val();
            /* Filter on the column (the index) of this element */
            //oTable.fnMultiFilter( { kk: this.value } );
            oTable.fnMultiFilter({"modelo": vsmodelo, "codigo": vscodigo, "aula": vsaula, "tipo": vstipo, "responsables": vsresponsables});
            //oTable.fnDraw();
            //oTable.fnMultiFilter( this.value, $("tfoot input").index(this) );
        });
        function removeClass(element)
        {
            var row = classTable.fnGetData(element);
            var id = row[0];
        }


        /********************************************************************/
        /*Table Tools Configuración botón añadir concepto   A RELLENAR       */
        /********************************************************************/
        TableTools.BUTTONS.boton = $.extend(true, TableTools.buttonBase, {
            "sNewLine": "<br>",
            "sButtonText": "Copy to element",
            "sDiv": ""
        });
        /*******************************************************************/
        /*Configuración TableTools                                         */
        /*******************************************************************/
        var oTableTools = new TableTools(oTable, {
            "sSwfPath": "/js/swf/copy_csv_xls_pdf.swf",
            "aButtons": [
                {
                    "sExtends": "boton",
                    "sButtonText": "Listado",
                    "fnClick": function(nButton, oConfig) {
                        window.location.href = '<?php echo $this->baseUrl("/incidencias/"); ?>';
                    }
                },
                {
                    "sExtends": "boton",
                    "sButtonText": "Nueva",
                    "fnClick": function(nButton, oConfig) {
                        window.location.href = '<?php echo $this->baseUrl("/incidencias/editar/"); ?>';
                    }
                }

            ]
        });
        $('#herramientas').before(oTableTools.dom.container);
        // Set the classes that TableTools uses to something suitable for Bootstrap
        $.extend(true, $.fn.DataTable.TableTools.classes, {
            "container": "btn-group",
            "buttons": {
                "normal": "btn",
                "disabled": "btn disabled"
            },
            "collection": {
                "container": "DTTT_dropdown dropdown-menu",
                "buttons": {
                    "normal": "",
                    "disabled": "disabled"
                }
            }
        });
        // Have the collection use a bootstrap compatible dropdown
        $.extend(true, $.fn.DataTable.TableTools.DEFAULTS.oTags, {
            "collection": {
                "container": "ul",
                "button": "li",
                "liner": "a"
            }
        });
        /*******************************************************************/
        /* EVENTOS DE LA PÁGINA                                            */
        /*******************************************************************/
        $.extend($.gritter.options, {
            /*class_name: 'gritter-light',*/
            position: 'bottom-right', // possibilities: bottom-left, bottom-right, top-left, top-right
            fade_in_speed: 100, // how fast notifications fade in (string or int)
            fade_out_speed: 100, // how fast the notices fade out
            time: 3000 // hang on the screen for...
        });
        $("#cancelar").click(function() {
            formulario.reset();
            $("#garantia").html("");
            $("#formulario").css("display", "none");
            $("#infoinventario").html("Selecciona primero el equipo desde el Inventario.");
        });
        /*Borrado*/
        $("#tabla").on('click', ".borrarbtn", function(e) {
            e.preventDefault();
            var nRow = $(this).parents('tr')[0];
            var aData = oTable.fnGetData(nRow);
            /*var jqTds = $('>td', nRow);*/
            id_inventario = aData.id_inventario;
            referencia = aData.modelo;
            $(".modal-body").html("<p> ¿Seguro que quieres borrar " + referencia + "?</p>");
        });
        $("#tabla").on('click', ".editarbtn", edicion);
        function edicion(e) {
            e.preventDefault();
            var nRow = $(this).parents('tr')[0];
            var aData = oTable.fnGetData(nRow);
            /*var jqTds = $('>td', nRow);*/
            formvalidator.resetForm();
            formulario.reset();
            $("#garantia").html("");
            $("#formulario").css("display", "block");
            puesto = (aData.puesto === null) ? "" : aData.puesto;
            responsables = (aData.responsables === null) ? "" : aData.responsables;
            id_aula = (aData.aulas_id_aula === null) ? "" : aData.aulas_id_aula;
            aula = (aData.aula === null) ? "" : aData.aula;
            /*Comprobamos la garantía*/
            var dosaños = 731;
            if (aData.fecha_adquisicion !== null && garantia(new Date(hoy()), new Date(aData.fecha_adquisicion)) < dosaños) {
                $("#garantia").html("El artículo está en garantía");
            }
            $("#estadomat").val(aData.estado);
            var equipo = '<b>Modelo:</b> ' + aData.modelo + '<br/> <b>Código: </b>' + aData.codigo + '<br/><b> Aula: </b> ' + aula + '<br/> <b>Puesto: </b>' + puesto + '<br/><b>Responsables Aula: </b> ' + responsables;
            /*cargamos solo el inventario ya que es para nuevas incidencias*/
            $("#infoinventario").html(equipo);
            $("#inventario_id_inventario").val(aData.id_inventario);
            /*Cargamos vía ajax la lista de profesores de departamento, que serán candidatos a la asignación de la incidencia*/
            /*primero borramos los que había*/
            $("#responsable").find('option').remove().end();
            id_departamento = aData.id_departamento;
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: "<?php echo $this->baseUrl('/aulas/getresponsables/'); ?>",
                async: false,
                // you can use an object here
                data: {'id_aula': id_aula},
                //includes the response status (e.g. 404 not found) and an error message
                error: function(xhr, status, error) {
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: '¡Error al obtener los responsables!',
                        // (string | mandatory) the text inside the notification
                        text: 'No se han podido obtener los profesores responsables del aula ',
                        image: '/img/block.png'
                    });
                },
                success: function(data) {
                    $("html").css('cursor', 'auto');
                    if (data["estado"]) {
                        var imagen = '/img/fail.png';
                        var texto = "Ha ocurrido un error en la consulta a la bbdd: <br/>" + data["respuesta"];
                        $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: 'Alta Incidencia ',
                            // (string | mandatory) the text inside the notification
                            text: texto,
                            image: imagen

                        });
                    }
                    else {
                        /*rellenamos el combo con los profesores del departamento:*/
                        $.each(data, function(val, text) {
                            $("#responsable").append($('<option></option>').val(val).html(text));
                        });
                        /*los ordenamos por texto y no por valor*/
                        var options = $('#responsable option');
                        var arr = options.map(function(_, o) {
                            return {t: $(o).text(), v: o.value};
                        }).get();
                        arr.sort(function(o1, o2) {
                            return o1.t > o2.t ? 1 : o1.t < o2.t ? -1 : 0;
                        });
                        options.each(function(i, o) {
                            o.value = arr[i].v;
                            $(o).text(arr[i].t);
                        });
                        /*seleccionamos el usuario actual si existe*/
                        $("#responsable").val("<?php echo $this->id_usuario ?>");
                        /*Si existe responsable, mejor este*/
                        var selectOptionText = $("#infoinventario ul li").text();
                        $("#responsable").find("option").filter(function(index) {
                            return selectOptionText === $(this).text();
                        }).attr("selected", "selected");
                    }
                },
                complete: {
                }
            });
            $('html, body').animate({
                scrollTop: $("#content").offset().top
            }, 20);
        }
        $("#guardar").click(function(e) {
            e.preventDefault();
            $("html").css('cursor', 'wait');
            resultado = $("#formulario").validate().form();
            if (!resultado) {
                $("html").css('cursor', 'auto');
                return;
            }
            /*si el tipo hidden viene vacío el ajax no lo procesa, lo tenemos que extraer antes de la cadena*/
            var dato = $("#modelo").val();
            var datos = $("#formulario").serialize() + "&id_aula=" + id_aula;
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: "<?php echo $this->baseUrl('/incidencias/guardar/'); ?>",
                async: false,
                // you can use an object here
                data: datos,
                //includes the response status (e.g. 404 not found) and an error message
                error: function(xhr, status, error) {
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: '¡Error al guardar el registro!',
                        // (string | mandatory) the text inside the notification
                        text: 'No se ha guardado la Incidencia',
                        image: '/img/block.png'
                    });
                },
                success: function(data) {
                    $("html").css('cursor', 'auto');
                    if (data["estado"]) {
                        var imagen = '/img/fail.png';
                        var texto = "Ha ocurrido un error en la inserción en la bbdd: <br/>" + data["respuesta"];
                    }
                    else
                    {
                        var imagen = '/img/ok.png';
                        var texto = "Se ha añadido la Incidencia";
                        $("#infoinventario").html("Selecciona primero el equipo desde el Inventario.");
                        formulario.reset();
                        $("#garantia").html("");
                        $("#formulario").css("display", "none");
                        window.location.href = '<?php echo $this->baseUrl('/incidencias/index/insertada/ok'); ?>';
                    }
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: 'Alta Incidencia ',
                        // (string | mandatory) the text inside the notification
                        text: texto,
                        image: imagen

                    });
                    oTable.fnStandingRedraw();
                },
                complete: {
                }
            });
        });
        $('#fecha_incidencia')
                .datepicker({
                    format: 'dd-mm-yyyy',
                    weekStart: 1,
                    language: "es",
                    todayHighlight: true,
                    autoclose: true
                });
        $("#estadomat").change(function() {
            var estado = $("#estadomat").val();
            if (estado == "Baja")
                $("#estadoinc").val("Cerrada");
        });
        $("#estadoinc").change(function() {
            var estadoinc = $("#estadoinc").val();
            /*Si la incidencia se cierra, podemos poner valores a la descripción de detalle y a la solución*/
            if (estadoinc == "Cerrada") {
                $("#solucion").css("display", "block");
                $("#lblsolucion").css("visibility", "visible");
                $("#lblsolucion_det").css("visibility", "visible");
                $("#solucion_det").css("display", "block");
            }
            else
            {
                $("#solucion").css("display", "none");
                $("#solucion_det").css("display", "none");
                $("#lblsolucion").css("visibility", "hidden");
                $("#lblsolucion_det").css("visibility", "hidden");
            }

            if (estadoinc == "Abierta en Proveedor") {
                $.gritter.add({
                    // (string | mandatory) the heading of the notification
                    title: 'Incidencia con Proveedor',
                    // (string | mandatory) the text inside the notification
                    text: 'En principio las incidencias con proveedores se asignan al Jefe de Departamento',
                    image: '/img/ok.png'
                });
                /*ponemos como responsable al jefe de departamento*/
                $.ajax({
                    type: 'POST',
                    dataType: 'json',
                    url: "<?php echo $this->baseUrl('/departamentos/getjefedepartamento/'); ?>",
                    async: false,
                    // you can use an object here
                    data: {'id_departamento': id_departamento},
                    //includes the response status (e.g. 404 not found) and an error message
                    error: function(xhr, status, error) {
                        $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: '¡Error al obtener el jefe del departamento!',
                            // (string | mandatory) the text inside the notification
                            text: 'No se han podido obtener los profesores del departamento ',
                            image: '/img/block.png'
                        });
                    },
                    success: function(data) {
                        $("html").css('cursor', 'auto');
                        if (data["estado"]) {
                            var imagen = '/img/fail.png';
                            var texto = "Ha ocurrido un error en la consulta a la bbdd: <br/>" + data["respuesta"];
                        }
                        else {
                            /*rellenamos el combo con los profesores del departamento:*/
                            $.each(data, function(val, text) {
                                $("#responsable").val(val);
                            });
                        }
                    },
                    complete: {
                    }
                });
            }
        });
        $('#responsable').focus(function() {
            if (!$("#responsable").val()) {
                $.gritter.add({
                    // (string | mandatory) the heading of the notification
                    title: 'Responsables del aula',
                    // (string | mandatory) the text inside the notification
                    text: 'Falta configurar los responsables del aula ',
                    image: '/img/block.png'
                });
            }
        });
        $("#mnuincidencias").addClass("active");
    }); /*Fin de document.ready*/
</script>
<div class="row-fluid">
    <?php echo $this->partial('menu.php'); ?>
    <noscript>
    <div class="alert alert-block span11">
        <h4 class="alert-heading">Aviso!</h4>
        <p>Necesitas <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> para poder visualizar correctamente esta página.</p>
    </div>
    </noscript>

    <!-- start: Content -->
    <!-- start: Content -->
    <div id="content" class="span11">
        <div class="row-fluid">
            <h1 id="titulo">Alta de Incidencias</h1>
            <div id="herramientas"></div>
            <p><span id="garantia" class="label label-important"></span></p>
        </div>
        <div class="row-fluid">
            <div class="box span12">
                <div class="box-header" data-original-title>
                    <h2><i class="halflings-icon edit"></i><span class="break"></span>Nueva Incidencia</h2>
                    <div class="box-icon">
                        <a href="#" id="toggle-fullscreen" class="hidden-phone hidden-tablet"><i class="halflings-icon fullscreen"></i></a>
                        <a href="#" id="minnuevo" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                        <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                    </div>
                </div>
                <div class="box-content">
                    <p id="infoinventario" class="text-info">Selecciona primero el equipo desde el Inventario.</p>
                    <form style="display:none;" method="<?php echo $this->formulario->getMethod() ?>" action="<?php echo $this->formulario->getAction() ?>" name="<?php echo $this->formulario->getName() ?>" id="<?php echo $this->formulario->getName() ?>">
                        <div class="row-fluid">
                            <div class="span12">
                                <div class="row-fluid">
                                    <div class="span2">
                                        <label>Fecha</label>
                                        <?php echo $this->formulario->fecha_incidencia->renderViewHelper(); ?>
                                    </div><!--/span-->
                                    <div class="span2">
                                        <label>Prioridad</label>
                                        <?php echo $this->formulario->prioridad->renderViewHelper(); ?>
                                    </div><!--/span-->
                                    <div class="span2">
                                        <label>Estado Material</label>
                                        <?php echo $this->formulario->estadomat->renderViewHelper(); ?>
                                    </div><!--/span-->
                                    <div class="span2">
                                        <label>Estado Incidencia</label>
                                        <?php echo $this->formulario->estadoinc->renderViewHelper(); ?>
                                    </div><!--/span-->
                                    <div class="span4">
                                        <label>Asignada a</label>
                                        <?php echo $this->formulario->responsable->renderViewHelper(); ?>
                                    </div><!--/span-->

                                </div><!--/row-->
                                <div class="row-fluid">
                                    <div class="span12">
                                        <label>Causa</label>
                                        <?php echo $this->formulario->id_incidencia->renderViewHelper(); ?>
                                        <?php echo $this->formulario->inventario_id_inventario->renderViewHelper(); ?>
                                        <?php echo $this->formulario->causa->renderViewHelper(); ?>
                                    </div><!--/span-->
                                </div><!--/row-->
                                <div class="row-fluid">
                                    <label>Descripción</label>

                                    <?php echo $this->formulario->descripcion->renderViewHelper(); ?>
                                </div><!--/row-->
                                <div class="row-fluid">
                                    <div class="span12">
                                        <label id="lblsolucion" style="visibility:hidden;">Solución</label>
                                        <?php echo $this->formulario->solucion->renderViewHelper(); ?>
                                    </div><!--/span-->
                                </div><!--/row-->
                                <div class="row-fluid">
                                    <label id="lblsolucion_det" style="visibility:hidden;">Descripción solución</label>

                                    <?php echo $this->formulario->solucion_det->renderViewHelper(); ?>
                                </div><!--/row-->
                                <div class="form-actions">
                                    <?php echo $this->formulario->guardar->renderViewHelper(); ?>
                                    <?php echo $this->formulario->cancelar->renderViewHelper(); ?>
                                </div><!--/form-actions-->
                            </div>
                        </div>
                    </form>
                </div>
            </div><!--/span-->
        </div><!--/row-->
        <div class="row-fluid">
            <div class="box span12">
                <div class="box-header" data-original-title>
                    <h2><i class="fa-icon-hdd"></i><span class="break"></span>Inventario</h2>
                    <div class="box-icon">
                        <a href="#" id="toggle-fullscreen" class="hidden-phone hidden-tablet"><i class="halflings-icon fullscreen"></i></a>
                        <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                        <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                    </div>
                </div>
                <div class="box-content">
                    <table id="tabla" class="table table-striped table-bordered bootstrap-datatable datatable">
                        <thead>
                            <tr>
                                <th>
                        <div class="input-append">
                            <input type="text" id="smodelo"  placeholder="Filtrar modelo" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div>
                        </th>                                
                        <th>
                        <div class="input-append" >
                            <input type="text" id="scodigo"  placeholder="Filtrar código" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div>
                        </th>
                        <th>
                        <div class="input-append" style="display:none;">
                            <input type="text" id="sfechacompra"  placeholder="Filtrar fecha" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div>
                        </th>  
                        <th>
                        <div class="input-append">
                            <input type="text" id="saula"  placeholder="Filtrar aula" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div>       
                        </th>
                        <th>
                        <div class="input-append" style="display:none;">
                            <input type="text" id="saula"  placeholder="Filtrar puesto" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div> 

                        </th>                                  
                        <th>
                        <div class="input-append">
                            <input type="text" id="stipo"  placeholder="Filtrar tipo" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div> 
                        </th>
                        <th>
                        <div class="input-append">
                            <input type="text" id="sresponsables"  placeholder="Filtrar responsables" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div> 
                        </th>
                        <th><!--acciones--></th>  
                        <th><!--Id Inventario--></th>
                        <th><!--Aulas_id_aula--></th>
                        <th><!--tipos_id_tipo--></th>
                        <th><!--id_proveedor--></th>
                        <th><!--Proveedor--></th>
                        <th><!--Estado--></th>
                        <th><!--Obs--></th>
                        <th><!--id_departamento--></th>
                        <th><!--Departamento--></th>
                        </tr>
                        <tr>
                            <th title="Nombre del material en el inventario">Modelo</th>
                            <th title="Código del material según el centro">Código</th>
                            <th title="Fecha de compra del material">Fecha</th>
                            <th  title="Lugar de ubicación del material">Aula</th>
                            <th  title="Puesto de ubicación del material">Puesto</th>
                            <th title="Tipo de material">Tipo</th>
                            <th title="Usuarios responsables de las incidencias del material">Responsables</th>
                            <th title="Asignar incidencia o ver detalles de incidencias">Acciones</th>
                            <th>Id Inventario</th>
                            <th>Aulas_id_aula</th>
                            <th>tipos_id_tipo</th>
                            <th>id_proveedor</th>
                            <th title="Proveedor del material">Proveedor</th>
                            <th>Estado</th>
                            <th>Obs</th>
                            <th>id_departamento</th>
                            <th>Departamento</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                        <tfoot>
                        </tfoot>
                    </table>
                </div>
            </div><!--/span-->

        </div><!--/row-->

    </div><!--/#content.span11-->
</div><!--/fluid-row-->