<script type="text/javascript">
    $(document).ready(function() {
        /*******************************************************************/
        /* Validación formulario                                           */
        /*******************************************************************/
        var formvalidator = $("#formulario").validate({
            /*bug hacía el validate con la fecha "antigua", antes de la selección*/

            rules: {
                nombre: {
                    required: true
                },
                apellido: {
                    required: true
                },
                email: {
                    required: true,
                    email: true
                },
                id_departamento: {
                    required: true
                }
            },
            messages: {
                nombre: {
                    required: "Debes rellenar el nombre"
                },
                apellido: {
                    required: "Debes rellenar el apellido"
                },
                email: {
                    required: "Debes rellenar el email"
                },
                id_departamento: {
                    required: "Debes rellenar el departamento al que pertenece"
                }
            }
        });

        /*******************************************************************/
        /*Configuración datatables                                         */
        /*******************************************************************/
        $.extend($.fn.dataTableExt.oStdClasses, {
            "sWrapper": "dataTables_wrapper form-inline"
        });

        $.fn.dataTableExt.oApi.fnStandingRedraw = function(oSettings) {
            if (oSettings.oFeatures.bServerSide === false) {
                var before = oSettings._iDisplayStart;
                oSettings.oApi._fnReDraw(oSettings);
                // iDisplayStart has been reset to zero - so lets change it back
                oSettings._iDisplayStart = before;
                oSettings.oApi._fnCalculateEnd(oSettings);
            }
            // draw the 'current' page
            oSettings.oApi._fnDraw(oSettings);
        };
        /* API method to get paging information */
        $.fn.dataTableExt.oApi.fnPagingInfo = function(oSettings)
        {
            return {
                "iStart": oSettings._iDisplayStart,
                "iEnd": oSettings.fnDisplayEnd(),
                "iLength": oSettings._iDisplayLength,
                "iTotal": oSettings.fnRecordsTotal(),
                "iFilteredTotal": oSettings.fnRecordsDisplay(),
                "iPage": Math.ceil(oSettings._iDisplayStart / oSettings._iDisplayLength),
                "iTotalPages": Math.ceil(oSettings.fnRecordsDisplay() / oSettings._iDisplayLength)
            };
        }
        /* Bootstrap style pagination control */
        $.extend($.fn.dataTableExt.oPagination, {
            "bootstrap": {
                "fnInit": function(oSettings, nPaging, fnDraw) {
                    var oLang = oSettings.oLanguage.oPaginate;
                    var fnClickHandler = function(e) {
                        e.preventDefault();
                        if (oSettings.oApi._fnPageChange(oSettings, e.data.action)) {
                            fnDraw(oSettings);
                        }
                    };

                    $(nPaging).addClass('pagination').append(
                            '<ul>' +
                            '<li class="prev disabled"><a href="#">&larr; ' + oLang.sPrevious + '</a></li>' +
                            '<li class="next disabled"><a href="#">' + oLang.sNext + ' &rarr; </a></li>' +
                            '</ul>'
                            );
                    var els = $('a', nPaging);
                    $(els[0]).bind('click.DT', {action: "previous"}, fnClickHandler);
                    $(els[1]).bind('click.DT', {action: "next"}, fnClickHandler);
                },
                "fnUpdate": function(oSettings, fnDraw) {
                    var iListLength = 5;
                    var oPaging = oSettings.oInstance.fnPagingInfo();
                    var an = oSettings.aanFeatures.p;
                    var i, j, sClass, iStart, iEnd, iHalf = Math.floor(iListLength / 2);

                    if (oPaging.iTotalPages < iListLength) {
                        iStart = 1;
                        iEnd = oPaging.iTotalPages;
                    }
                    else if (oPaging.iPage <= iHalf) {
                        iStart = 1;
                        iEnd = iListLength;
                    } else if (oPaging.iPage >= (oPaging.iTotalPages - iHalf)) {
                        iStart = oPaging.iTotalPages - iListLength + 1;
                        iEnd = oPaging.iTotalPages;
                    } else {
                        iStart = oPaging.iPage - iHalf + 1;
                        iEnd = iStart + iListLength - 1;
                    }

                    for (i = 0, iLen = an.length; i < iLen; i++) {
                        // Remove the middle elements
                        $('li:gt(0)', an[i]).filter(':not(:last)').remove();

                        // Add the new list items and their event handlers
                        for (j = iStart; j <= iEnd; j++) {
                            sClass = (j == oPaging.iPage + 1) ? 'class="active"' : '';
                            $('<li ' + sClass + '><a href="#">' + j + '</a></li>')
                                    .insertBefore($('li:last', an[i])[0])
                                    .bind('click', function(e) {
                                        e.preventDefault();
                                        oSettings._iDisplayStart = (parseInt($('a', this).text(), 10) - 1) * oPaging.iLength;
                                        fnDraw(oSettings);
                                    });
                        }

                        // Add / remove disabled classes from the static elements
                        if (oPaging.iPage === 0) {
                            $('li:first', an[i]).addClass('disabled');
                        } else {
                            $('li:first', an[i]).removeClass('disabled');
                        }

                        if (oPaging.iPage === oPaging.iTotalPages - 1 || oPaging.iTotalPages === 0) {
                            $('li:last', an[i]).addClass('disabled');
                        } else {
                            $('li:last', an[i]).removeClass('disabled');
                        }
                    }
                }
            }
        });


        $.fn.dataTableExt.oApi.fnMultiFilter = function(oSettings, oData) {
            for (var key in oData)
            {
                if (oData.hasOwnProperty(key))
                {
                    for (var i = 0, iLen = oSettings.aoColumns.length; i < iLen; i++)
                    {
                        if (oSettings.aoColumns[i].sName == key)
                        {
                            /* Add single column filter */
                            oSettings.aoPreSearchCols[ i ].sSearch = oData[key];
                            break;
                        }
                    }
                }
            }
            this.oApi._fnReDraw(oSettings);
        };

        /******************************************************************/
        /* INICIALIZACIÓN DATATABLES: Configuración columnas y script php */
        /******************************************************************/
        oTable = $('#tabla').dataTable({
            "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span12'i><'span12 center'p>>",
            /*"<'row-fluid'<'span6'T><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",*/
            "sAjaxSource": "<?php echo $this->baseUrl("/php/usuarios.php"); ?>",
            "bProcessing": true,
            "bServerSide": true,
            "bStateSave": true,
            "bAutoWidth": false,
            "sPaginationType": "bootstrap",
            "fnInitComplete": function() {
                var oSettings = $('#tabla').dataTable().fnSettings();
                for (var i = 0; i < oSettings.aoPreSearchCols.length; i++) {
                    if (oSettings.aoPreSearchCols[i].sSearch.length > 0) {
                        $("thead input, thead select")[i].value = oSettings.aoPreSearchCols[i].sSearch;
                        // $("tfoot input")[i].className = "";
                    }
                }
            },
            "aoColumns": [
                {
                    "mData": "nombrecompleto",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "nombrecompleto",
                    "sWidth": "60px"
                },
                {
                    "mData": "estado",
                    "mRender": function(data, type, full) {
                        if (data === "1")
                            return '<span class="label label-success">Activo</span>';
                        return '<span class="label">Bloqueado</span>';
                    },
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "estado",
                    "sWidth": "100px"
                },
                {
                    "mData": "email",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "email"
                },
                {
                    "mData": "departamento",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "departamento"
                },
                {
                    "mData": "perfil",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "perfil",
                    "sWidth": "100px"
                },
                {
                    "mData": "aulas",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "aulas"
                },
                {
                    "mData": "estado",
                    "sClass": "valignCenter accion",
                    "mRender": function(data, type, full) {
                        if (data === "0")
                            return '<a title="Editar datos del usuario" style="margin:3px;" class="btn btn-info editarbtn" href="#"><i class="halflings-icon edit halflings-icon"></i></a><a title="Borrar el usuario de la aplicación" data-toggle="modal" href="#deleteModal" style="margin:3px;" class="btn btn-danger borrarbtn"><i class="halflings-icon trash halflings-icon"></i></a><a title="Permitir el acceso del usuario a la aplicación" style="margin:3px;" class="btn btn-success estadobtn" href="#"><i class="halflings-icon ok halflings-icon"></i></a>';
                        else
                            return '<a title="Editar datos del usuario" style="margin:3px;" class="btn btn-info editarbtn" href="#"><i class="halflings-icon edit halflings-icon"></i></a><a title="Borrar el usuario de la aplicación" data-toggle="modal" href="#deleteModal" style="margin:3px;" class="btn btn-danger borrarbtn"><i class="halflings-icon trash halflings-icon"></i></a><a title="Bloquear el acceso del usuario a la aplicación" style="margin:3px;" class="btn btn-warning estadobtn" href="#"><i class="halflings-icon ban-circle halflings-icon"></i></a>';
                    },
                    "bSortable": false,
                    "bSearchable": false,
                    "sWidth": "140px"
                },
                {
                    "mData": "id_usuario",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false

                },
                {
                    "mData": "nombre",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                },
                {
                    "mData": "apellido",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                },
                {
                    "mData": "departamentos_id_departamento",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                },
                {
                    "mData": "id_aulas",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                },
                {
                    "mData": "id_perfil",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                }

            ],
            "aaSorting": [[0, "asc"]],
            "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
            "oLanguage": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros por página",
                "sZeroRecords": "No se encontraron resultados",
                "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                "sInfoFiltered": "(Filtrado de _MAX_ registros en total)",
                "sLoadingRecords": "Por favor espere - cargando...",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sPrevious": "Anterior",
                    "sNext": "Siguiente",
                    "sLast": "Último"
                }
            },
            "fnDrawCallback": function() {
                $('#tabla tbody td:not(.accion)').click(edicion);

                $('#tabla tbody tr').hover(function() {
                    $(this).css('cursor', 'pointer');
                }, function() {
                    $(this).css('cursor', 'auto');
                });
            }
        });

        $(".sborrar").click(function() {
            $(this).prev().val("");
            $("thead input").keyup();
        });

        $("thead input, thead select").on("click keyup", function() {
            vsnombrecompleto = $("#snombrecompleto").val();
            vsestado = $("#sestado").val();
            vsemail = $("#semail").val();
            vsdepartamento = $("#sdepartamento").val();
            vsperfil = $("#sperfil").val();
            vsaulas = $("#saulas").val();
            /* Filter on the column (the index) of this element */

            //oTable.fnMultiFilter( { kk: this.value } );
            oTable.fnMultiFilter({"nombrecompleto": vsnombrecompleto, "estado": vsestado, "email": vsemail, "departamento": vsdepartamento, "perfil": vsperfil, "aulas": vsaulas});
            //oTable.fnDraw();
            //oTable.fnMultiFilter( this.value, $("tfoot input").index(this) );
        });






        function removeClass(element)
        {
            var row = classTable.fnGetData(element);
            var id = row[0];
        }


        /********************************************************************/
        /*Table Tools Configuración botón añadir concepto   A RELLENAR       */
        /********************************************************************/
        TableTools.BUTTONS.boton = $.extend(true, TableTools.buttonBase, {
            "sNewLine": "<br>",
            "sButtonText": "Copy to element",
            "sDiv": ""
        });
        /*******************************************************************/
        /*Configuración TableTools                                         */
        /*******************************************************************/
        var oTableTools = new TableTools(oTable, {
            "sSwfPath": "/js/swf/copy_csv_xls_pdf.swf",
            "aButtons": [
                {
                    "sExtends": "boton",
                    "sButtonText": "Listado",
                    "fnClick": function(nButton, oConfig) {
                        //event.preventDefault();
                        showList();
                    }
                },
                {
                    "sExtends": "boton",
                    "sButtonText": "Nuevo",
                    "fnClick": function(nButton, oConfig) {
                        //event.preventDefault();
                        showForm();
                        resetearFormulario("Nuevo Usuario", formulario, formvalidator);
                    }
                },
                {
                    "sExtends": "xls",
                    "sButtonText": "Excel",
                    "mColumns": [0, 1, 2, 3, 4, 5, 8, 9],
                    "sFileName": "listado_usuarios.xls"
                }

            ]
        });
        $('#herramientas').before(oTableTools.dom.container);
        // Set the classes that TableTools uses to something suitable for Bootstrap
        $.extend(true, $.fn.DataTable.TableTools.classes, {
            "container": "btn-group",
            "buttons": {
                "normal": "btn",
                "disabled": "btn disabled"
            },
            "collection": {
                "container": "DTTT_dropdown dropdown-menu",
                "buttons": {
                    "normal": "",
                    "disabled": "disabled"
                }
            }
        });

        // Have the collection use a bootstrap compatible dropdown
        $.extend(true, $.fn.DataTable.TableTools.DEFAULTS.oTags, {
            "collection": {
                "container": "ul",
                "button": "li",
                "liner": "a"
            }
        });




        /*******************************************************************/
        /* EVENTOS DE LA PÁGINA                                            */
        /*******************************************************************/
        $.extend($.gritter.options, {
            /*class_name: 'gritter-light',*/
            position: 'bottom-right', // possibilities: bottom-left, bottom-right, top-left, top-right
            fade_in_speed: 100, // how fast notifications fade in (string or int)
            fade_out_speed: 100, // how fast the notices fade out
            time: 3000 // hang on the screen for...
        });
        $("#cancelar").click(function() {
            resetearFormulario("Nuevo Usuario", formulario, formvalidator);
            showList();
        });


        /*Borrado*/
        $("#tabla").on('click', ".borrarbtn", function(e) {
            e.preventDefault();          
            var nRow = $(this).parents('tr')[0];
            var aData = oTable.fnGetData(nRow);
            /*var jqTds = $('>td', nRow);*/
            id_usuario = aData.id_usuario;
            referencia = aData.nombrecompleto;
            $(".modal-body").html("<p> ¿Seguro que quieres borrar al usuario " + referencia + "?</p>");
        });

        $("#borrar").click(function() {
            $("html").css('cursor', 'wait');
            $('#deleteModal').modal('hide');
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: "<?php echo $this->baseUrl() . '/usuarios/borrar' ?>",
                async: false,
                // you can use an object here
                data: {id_usuario: id_usuario},
                //includes the response status (e.g. 404 not found) and an error message
                error: function(xhr, status, error) {
                    $("html").css('cursor', 'auto');
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: '¡Error al borrar el registro!',
                        // (string | mandatory) the text inside the notification
                        text: 'No se ha eliminado a ' + referencia + ' del listado de Usuarios',
                        image: '/img/block.png'
                    });
                },
                success: function(data) {
                    $("html").css('cursor', 'auto');
                    if (data["estado"]) {
                        var imagen = '/img/fail.png';
                        var texto = "Ha ocurrido un error en la eliminación de la bbdd: <br/>" + data["respuesta"];
                    }
                    else
                    {
                        var imagen = '/img/ok.png';
                        var texto = "Se ha eliminado a " + referencia + ' del listado de Usuarios';
                    }
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: 'Usuarios ',
                        text: texto,
                        image: imagen

                    });
                    //formulario.reset();
                    oTable.fnStandingRedraw();
                }

            });
        });
        $("#tabla").on('click', ".editarbtn", edicion);
        function edicion(e) {
            var nRow = $(this).parents('tr')[0];
            var aData = oTable.fnGetData(nRow);
            /*var jqTds = $('>td', nRow);*/
            formulario.reset();
            formvalidator.resetForm();
            $("#titulo").html("<i class='halflings-icon edit'></i><span class='break'></span>Modificar Usuario " + aData.nombrecompleto);
            $("#id_usuario").val(aData.id_usuario);
            $("#nombre").val(aData.nombre);
            $("#apellido").val(aData.apellido);
            $("#perfil").val(aData.id_perfil);
            $("#estado").val(aData.estado);
            $("#email").val(aData.email);
            if (aData.id_departamento !== null) {
                var myArray = aData.departamentos_id_departamento.split(",");
                for (var i = 0; i < myArray.length; i++) {
                    myArray[i] = +myArray[i];
                }
            }
            $("#departamentos_id_departamento").val(myArray);
            if (aData.id_aulas !== null) {
                myArray = aData.id_aulas.split(",");
                for (var i = 0; i < myArray.length; i++) {
                    myArray[i] = +myArray[i];
                }
                $("#id_aulas").val(myArray);
            }
            showForm();
             $('html, body').animate({
                scrollTop: $("body").offset().top
            }, 0);
        }



        $("#guardar").click(function(e) {
            e.preventDefault();
            $("html").css('cursor', 'wait');
            resultado = $("#formulario").validate().form();
            if (!resultado) {
                $("html").css('cursor', 'auto');
                return;
            }
            /*si el tipo hidden viene vacío el ajax no lo procesa, lo tenemos que extraer antes de la cadena*/
            var dato = $("#nombre").val() + " " + $("#apellido").val();
            var datos = $("#formulario").serialize();
            /*alert (datos);*/
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: "<?php echo $this->baseUrl('/usuarios/guardar/'); ?>",
                async: false,
                // you can use an object here
                data: datos,
                //includes the response status (e.g. 404 not found) and an error message
                error: function(xhr, status, error) {
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: '¡Error al guardar el registro!',
                        // (string | mandatory) the text inside the notification
                        text: 'No se ha guardado a ' + dato + ' en el listado de Usuarios',
                        image: '/img/block.png'
                    });
                    $("html").css('cursor', 'auto');
                },
                success: function(data) {
                    $("html").css('cursor', 'auto');
                    if (data["estado"]) {
                        var imagen = '/img/fail.png';
                        var texto = "Ha ocurrido un error en la inserción en la bbdd: <br/>" + data["respuesta"];
                    }
                    else
                    {
                        var imagen = '/img/ok.png';
                        var texto = "Se ha añadido a " + dato + ' en el listado de Usuarios';
                        resetearFormulario("Nuevo Usuario", formulario, formvalidator);
                    }
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: 'Usuarios ',
                        // (string | mandatory) the text inside the notification
                        text: texto,
                        image: imagen

                    });
                    oTable.fnStandingRedraw();
                    showList();
                }
            });
        });
        $("#tabla").on('click', ".estadobtn", function(e) {
            e.preventDefault();
            var nRow = $(this).parents('tr')[0];
            var aData = oTable.fnGetData(nRow);
            var id_usuario = aData.id_usuario;
            var estado;
            var dato = aData.nombre + " " + aData.apellido;
            if (aData.estado == 0) {
                estado = 1;
                mensajito = "Se ha concedido el acceso al usuario " + dato;
            } else
            {
                estado = 0;
                mensajito = "Se ha denegado el acceso al usuario " + dato;
            }
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: "<?php echo $this->baseUrl('/usuarios/cambiarestado/'); ?>",
                async: false,
                // you can use an object here
                data: {'id_usuario': id_usuario, 'estado': estado},
                //includes the response status (e.g. 404 not found) and an error message
                error: function(xhr, status, error) {
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: '¡Error al modificar el estado del usuario!',
                        // (string | mandatory) the text inside the notification
                        text: 'No se ha modificado el estado de ' + dato + ' en el listado de Usuarios',
                        image: '/img/block.png'
                    });
                    $("html").css('cursor', 'auto');
                },
                success: function(data) {
                    $("html").css('cursor', 'auto');
                    if (data["estado"]) {
                        var imagen = '/img/fail.png';
                        var texto = "Ha ocurrido un error en la inserción en la bbdd: <br/>" + data["respuesta"];
                    }
                    else
                    {
                        var imagen = '/img/ok.png';
                        var texto = mensajito;
                    }
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: 'Usuarios ',
                        // (string | mandatory) the text inside the notification
                        text: texto,
                        image: imagen

                    });
                    oTable.fnStandingRedraw();
                }
            });
        });

        $("#mnuconf").addClass("active");


    }); /*Fin de document.ready*/
</script>
<div class="row-fluid">
    <?php echo $this->partial('menu.php'); ?> 
    <noscript>
    <div class="alert alert-block span11">
        <h4 class="alert-heading">Aviso!</h4>
        <p>Necesitas <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> para poder visualizar correctamente esta página.</p>
    </div>
    </noscript>

    <!-- start: Content -->
    <!-- start: Content -->
    <div id="content" class="span11">
        <div style="float:right;" class="btn-toolbar">
            <div class="btn-group">
                <a class="btn" href="/departamentos"><i class="fa-icon-home"></i><span class="hidden-tablet"> Departamentos</span></a>
                <a class="btn active" href="/usuarios"><i class="fa-icon-user"></i><span class="hidden-tablet"> Usuarios</span></a>
                <a class="btn" href="/aulas"><i class="fa-icon-sitemap"></i><span class="hidden-tablet"> Aulas</span></a>
                <a class="btn" href="/materiales"><i class="fa-icon-hdd"></i><span class="hidden-tablet"> Materiales</span></a>
                <a class="btn" href="/proveedores"><i class="fa-icon-shopping-cart"></i><span class="hidden-tablet"> Proveedores</span></a>
                <a class="btn" href="/permisos"><i class="fa-icon-key"></i><span class="hidden-tablet"> Permisos</span></a>
            </div>
        </div>
        <div class="row-fluid">
            <h1>Usuarios</h1>
            <div id="herramientas"></div>
        </div>

        <div class="row-fluid" id="divadd" style="display:none">

            <div class="box span12">
                <div class="box-header" data-original-title>
                    <h2 id="titulo"><i class="halflings-icon edit"></i><span class="break"></span>Nuevo Usuario</h2>
                    <div class="box-icon">
                        <a href="#" id="toggle-fullscreen" class="hidden-phone hidden-tablet"><i class="halflings-icon fullscreen"></i></a>
                        <a href="#" id="minnuevo" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                        <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                    </div>
                </div>
                <div class="box-content">
                    <form method="<?php echo $this->formulario->getMethod() ?>" action="<?php echo $this->formulario->getAction() ?>" name="<?php echo $this->formulario->getName() ?>" id="<?php echo $this->formulario->getName() ?>">
                        <div class="row-fluid">
                            <div class="span12">   
                                <div class="row-fluid">   
                                    <div class="span6">
                                        <label for="nombre">Nombre</label>
                                        <?php echo $this->formulario->id_usuario->renderViewHelper(); ?>  
                                        <?php echo $this->formulario->nombre->renderViewHelper(); ?>  
                                    </div><!--/span-->
                                    <div class="span6">
                                        <label for="apellido">Apellido</label>
                                        <?php echo $this->formulario->apellido->renderViewHelper(); ?>   
                                    </div><!--/span-->
                                </div><!--/row-->
                                <div class="row-fluid">
                                    <div class="span6">
                                        <label for="email">Correo electrónico</label>
                                        <?php echo $this->formulario->email->renderViewHelper(); ?>    
                                    </div><!--/span-->
                                    <div class="span6">
                                        <label for="departamentos_id_departamento">Departamento</label>
                                        <?php echo $this->formulario->departamentos_id_departamento->renderViewHelper(); ?>    
                                    </div><!--/span-->
                                </div><!--/row-->
                                <div class="row-fluid">
                                    <div class="span6">
                                        <label for="id_aulas">Aulas</label>
                                        <?php echo $this->formulario->id_aulas->renderViewHelper(); ?>    
                                    </div><!--/span-->
                                    <div class="span6">
                                        <label for="perfil">Perfil</label>
                                        <?php echo $this->formulario->perfil->renderViewHelper(); ?>    
                                    </div><!--/span-->
                                </div><!--/row-->
                                <div class="form-actions">               
                                    <?php echo $this->formulario->guardar->renderViewHelper(); ?> 
                                    <?php echo $this->formulario->cancelar->renderViewHelper(); ?> 
                                </div><!--/form-actions-->
                            </div>
                        </div>
                    </form>
                </div>
            </div><!--/span-->

        </div><!--/row-->
        <div class="row-fluid" id="divlist">		
            <div class="box span12">
                <div class="box-header" data-original-title>
                    <h2><i class="fa-icon-hdd"></i><span class="break"></span>Listado de Usuarios</h2>
                    <div class="box-icon">
                        <a href="#" id="toggle-fullscreen" class="hidden-phone hidden-tablet"><i class="halflings-icon fullscreen"></i></a>
                        <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                        <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                    </div>
                </div>
                <div class="box-content">
                    <table id="tabla" class="table table-striped table-bordered bootstrap-datatable datatable">
                        <thead>
                            <tr>
                                <th> <div class="input-append">
                            <input type="text" id="snombrecompleto"  placeholder="Filtrar nombre" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div></th>
                        <th> 
                            <select id="sestado" class="search_init" >
                                <option value="" selected>Filtrar estado</option>
                                <option value="1">Activo</option>
                                <option value="0">Bloqueado</option>
                            </select>

                        </th>
                        <th> <div class="input-append">
                            <input type="text" id="semail"  placeholder="Filtrar email" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div></th>
                        <th> <div class="input-append">
                            <input type="text" id="sdepartamento"  placeholder="Filtrar departamento" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div></th>
                        <th>                             <select id="sperfil"   class="search_init" >
                                <option value="" selected>Filtrar perfil</option>
                                <option value="Profesor">Profesor</option>
                                <option value="Jefe de Departamento">Jefe de Departamento</option>
                                <option value="Secretario">Secretario</option>
                                <option value="Jefe de Estudios">Jefe de Estudios</option>
                                <option value="Director">Director</option>
                            </select>
                        </th>                                
                        <th> <div class="input-append">
                            <input type="text" id="saulas"  placeholder="Filtrar aula" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div></th>
                        <th></th>                                
                        <th></th>                                
                        <th></th>
                        <th></th>  
                        <th></th>                                  
                        <th></th>
                        <th></th>
                        </tr>
                        <tr>
                            <th title="Nombre del usuario de la aplicación">Usuario</th>
                            <th title="Accesibilidad del usuario a la aplicación: activo o bloqueado ">Estado</th>                                
                            <th title="Correo electrónico del usuario, necesario para las comunicaciones">Email</th>
                            <th title="Departamento al que pertenece el usuario">Departamento</th>                                
                            <th title="Perfil del usuario, para la política de permisos">Perfil</th>
                            <th title="Aulas a las que accede el usuario, útil para recibir avisos de mantenimientos o incidencias">Aulas</th>                                  
                            <th title="Ver o modificar datos de los usuarios">Acciones</th>
                            <th>Id usuario</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Departamentos_id_departamento</th>  
                            <th>Id.Aulas</th>  
                            <th>id.perfil</th>
                        </tr>
                        </thead>  
                        <tbody></tbody>
                        <tfoot>
                        </tfoot>
                    </table>            
                </div>
            </div><!--/span-->

        </div><!--/row-->
        <!-- Formulario de borrado -->
        <div class="modal hide" id="deleteModal">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3>Borrar Usuarios</h3>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal">Cancelar</a>
                <a id="borrar" href="#" class="btn btn-primary">Borrar</a>
            </div>
        </div>
        <!-- end: Content -->
    </div><!--/#content.span11-->
</div><!--/fluid-row-->