<script type="text/javascript">
    $(document).ready(function() {
        /*******************************************************************/
        /* Validación formulario                                           */
        /*******************************************************************/
        var formvalidator = $("#formulario").validate({
            /*bug hacía el validate con la fecha "antigua", antes de la selección*/
            rules: {
                modelo: {
                    required: true
                }
            },
            messages: {
                modelo: {
                    required: "Debe rellenar el nombre del Modelo"
                }
            }
        });

        /*******************************************************************/
        /*Configuración datatables                                         */
        /*******************************************************************/
        $.extend($.fn.dataTableExt.oStdClasses, {
            "sWrapper": "dataTables_wrapper form-inline"
        });

        $.fn.dataTableExt.oApi.fnStandingRedraw = function(oSettings) {
            if (oSettings.oFeatures.bServerSide === false) {
                var before = oSettings._iDisplayStart;
                oSettings.oApi._fnReDraw(oSettings);
                // iDisplayStart has been reset to zero - so lets change it back
                oSettings._iDisplayStart = before;
                oSettings.oApi._fnCalculateEnd(oSettings);
            }
            // draw the 'current' page
            oSettings.oApi._fnDraw(oSettings);
        };
        /* API method to get paging information */
        $.fn.dataTableExt.oApi.fnPagingInfo = function(oSettings)
        {
            return {
                "iStart": oSettings._iDisplayStart,
                "iEnd": oSettings.fnDisplayEnd(),
                "iLength": oSettings._iDisplayLength,
                "iTotal": oSettings.fnRecordsTotal(),
                "iFilteredTotal": oSettings.fnRecordsDisplay(),
                "iPage": Math.ceil(oSettings._iDisplayStart / oSettings._iDisplayLength),
                "iTotalPages": Math.ceil(oSettings.fnRecordsDisplay() / oSettings._iDisplayLength)
            };
        };
        /* Bootstrap style pagination control */
        $.extend($.fn.dataTableExt.oPagination, {
            "bootstrap": {
                "fnInit": function(oSettings, nPaging, fnDraw) {
                    var oLang = oSettings.oLanguage.oPaginate;
                    var fnClickHandler = function(e) {
                        e.preventDefault();
                        if (oSettings.oApi._fnPageChange(oSettings, e.data.action)) {
                            fnDraw(oSettings);
                        }
                    };

                    $(nPaging).addClass('pagination').append(
                            '<ul>' +
                            '<li class="prev disabled"><a href="#">&larr; ' + oLang.sPrevious + '</a></li>' +
                            '<li class="next disabled"><a href="#">' + oLang.sNext + ' &rarr; </a></li>' +
                            '</ul>'
                            );
                    var els = $('a', nPaging);
                    $(els[0]).bind('click.DT', {action: "previous"}, fnClickHandler);
                    $(els[1]).bind('click.DT', {action: "next"}, fnClickHandler);
                },
                "fnUpdate": function(oSettings, fnDraw) {
                    var iListLength = 5;
                    var oPaging = oSettings.oInstance.fnPagingInfo();
                    var an = oSettings.aanFeatures.p;
                    var i, j, sClass, iStart, iEnd, iHalf = Math.floor(iListLength / 2);

                    if (oPaging.iTotalPages < iListLength) {
                        iStart = 1;
                        iEnd = oPaging.iTotalPages;
                    }
                    else if (oPaging.iPage <= iHalf) {
                        iStart = 1;
                        iEnd = iListLength;
                    } else if (oPaging.iPage >= (oPaging.iTotalPages - iHalf)) {
                        iStart = oPaging.iTotalPages - iListLength + 1;
                        iEnd = oPaging.iTotalPages;
                    } else {
                        iStart = oPaging.iPage - iHalf + 1;
                        iEnd = iStart + iListLength - 1;
                    }

                    for (i = 0, iLen = an.length; i < iLen; i++) {
                        // Remove the middle elements
                        $('li:gt(0)', an[i]).filter(':not(:last)').remove();

                        // Add the new list items and their event handlers
                        for (j = iStart; j <= iEnd; j++) {
                            sClass = (j == oPaging.iPage + 1) ? 'class="active"' : '';
                            $('<li ' + sClass + '><a href="#">' + j + '</a></li>')
                                    .insertBefore($('li:last', an[i])[0])
                                    .bind('click', function(e) {
                                        e.preventDefault();
                                        oSettings._iDisplayStart = (parseInt($('a', this).text(), 10) - 1) * oPaging.iLength;
                                        fnDraw(oSettings);
                                    });
                        }

                        // Add / remove disabled classes from the static elements
                        if (oPaging.iPage === 0) {
                            $('li:first', an[i]).addClass('disabled');
                        } else {
                            $('li:first', an[i]).removeClass('disabled');
                        }

                        if (oPaging.iPage === oPaging.iTotalPages - 1 || oPaging.iTotalPages === 0) {
                            $('li:last', an[i]).addClass('disabled');
                        } else {
                            $('li:last', an[i]).removeClass('disabled');
                        }
                    }
                }
            }
        });

        /******************************************************************/
        /* INICIALIZACIÓN DATATABLES: Configuración columnas y script php */
        /******************************************************************/
        oTable = $('#tabla').dataTable({
            "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span12'i><'span12 center'p>>",
            /*"<'row-fluid'<'span6'T><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",*/
            "fnServerParams": function(aoData) {
                aoData.push({"name": "id_inventario", "value": <?php echo $this->equipo->id_inventario; ?>});
            },
            "sAjaxSource": "<?php echo $this->baseUrl("/php/historial.php"); ?>",
            "bProcessing": true,
            "bServerSide": true,
            "bStateSave": true,
            "bAutoWidth": false,
            "sPaginationType": "bootstrap",
            "aoColumns": [
                {
                    "mData": "id_incidencia",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false

                },
                {
                    "mData": "tipo",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true
                },
                {
                    "mData": "fecha_incidencia",
                    "mRender": function(data, type, full) {
                        return fecha_ddmmyyyy(data);
                    },
                    "bSearchable": false,
                    "bVisible": true,
                    "bSortable": true
                },
                {
                    "mData": "causa",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": false

                },
                {
                    "mData": "responsable",
                    "bSearchable": false,
                    "bVisible": true,
                    "bSortable": true
                },
                {
                    "mData": "tipo",
                    "sClass": "center",
                    "mRender": function(data, type, full) {
                        return '<a  style="margin:3px;" class="btn btn-success historialbtn" href="<?php echo $this->baseUrl('/incidencias/editardet/id_incidencia/'); ?>' + data + '"><i class="halflings-icon search halflings-icon"></i></a>';
                    },
                    "bSortable": false,
                    "bSearchable": false

                }
            ],
            "aaSorting": [[1, "asc"]],
            "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
            "oLanguage": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros por página",
                "sZeroRecords": "No se encontraron resultados",
                "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                "sInfoFiltered": "(Filtrado de _MAX_ registros en total)",
                "sLoadingRecords": "Por favor espere - cargando...",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sPrevious": "Anterior",
                    "sNext": "Siguiente",
                    "sLast": "Último"
                }
            }
        });
        function removeClass(element)
        {
            var row = classTable.fnGetData(element);
            var id = row[0];
        }
        /*******************************************************************/
        /* EVENTOS DE LA PÁGINA                                            */
        /*******************************************************************/
        $.extend($.gritter.options, {
            /*class_name: 'gritter-light',*/
            position: 'bottom-right', // possibilities: bottom-left, bottom-right, top-left, top-right
            fade_in_speed: 100, // how fast notifications fade in (string or int)
            fade_out_speed: 100, // how fast the notices fade out
            time: 3000 // hang on the screen for...
        });
     

        /*Ver historial*/
        $("#tabla").on('click', ".historialbtn", function(e) {
            e.preventDefault();
            var nRow = $(this).parents('tr')[0];
            var aData = oTable.fnGetData(nRow);
            /*var jqTds = $('>td', nRow);*/
            tipo = aData.tipo;
            id_incidencia = aData.id_incidencia;
            if (tipo === "Mantenimiento") {
                window.location = "<?php echo $this->baseUrl('/mantenimientos/editardet/id_mantenimiento/'); ?>" + id_incidencia;
            }
            else {
                window.location = "<?php echo $this->baseUrl('/incidencias/editardet/id_incidencia/'); ?>" + id_incidencia;
            }
        });


        /*Datepicker para la fecha de compra*/
        $('#fecha_adquisicion')
                .datepicker({
                    format: 'dd-mm-yyyy',
                    weekStart: 1,
                    language: "es",
                    todayHighlight: true,
                    autoclose: true
                });
    }); /*Fin de document.ready*/
</script>
<div class="row-fluid">
    <?php echo $this->partial('menu.php'); ?> 
    <noscript>
    <div class="alert alert-block span11">
        <h4 class="alert-heading">Aviso!</h4>
        <p>Necesitas <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> para poder visualizar correctamente esta página.</p>
    </div>
    </noscript>

    <!-- start: Content -->
    <!-- start: Content -->
    <div id="content" class="span11">
        <div class="row-fluid">
            <h1>Histórico</h1>
        </div>
        <div class="row-fluid">
            <div class="box span12">
                <div class="box-header" data-original-title>
                    <h2 id="titulo"><i class="halflings-icon edit"></i><span class="break"></span>Material</h2>
                    <div class="box-icon">
                        <a href="#" id="toggle-fullscreen" class="hidden-phone hidden-tablet"><i class="halflings-icon fullscreen"></i></a>
                        <a href="#" id="minnuevo" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                        <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                    </div>
                </div>
                <div class="box-content">
                    <form method="<?php echo $this->formulario->getMethod() ?>" action="<?php echo $this->formulario->getAction() ?>" name="<?php echo $this->formulario->getName() ?>" id="<?php echo $this->formulario->getName() ?>">
                        <div class="row-fluid">
                            <div class="span12">   
                                <div class="row-fluid">   
                                    <div class="span5">
                                        <label for="proveedor">Modelo</label>
                                        <?php echo $this->formulario->id_inventario->renderViewHelper(); ?>  
                                        <?php echo $this->formulario->modelo->renderViewHelper(); ?>  
                                    </div><!--/span-->
                                    <div class="span2">
                                        <label>Código</label>
                                        <?php echo $this->formulario->codigo->renderViewHelper(); ?>   
                                    </div><!--/span-->
                                    <div class="span3">
                                        <label>Tipo</label>
                                        <?php echo $this->formulario->tipos_id_tipo->renderViewHelper(); ?>    
                                    </div><!--/span-->
                                    <div class="span2">
                                        <label>Estado</label>
                                        <?php echo $this->formulario->estado->renderViewHelper(); ?>      
                                    </div><!--/span-->
                                </div><!--/row-->
                                <div class="row-fluid">
                                    <div class="span4">
                                        <label>Proveedor</label>
                                        <?php echo $this->formulario->proveedores_id_proveedor->renderViewHelper(); ?>    
                                    </div><!--/span-->
                                    <div class="span2">
                                        <label>Fecha compra</label>
                                        <?php echo $this->formulario->fecha_adquisicion->renderViewHelper(); ?>       
                                    </div><!--/span-->
                                    <div class="span3">
                                        <label>Departamento</label>
                                        <?php echo $this->formulario->departamentos_id_departamento->renderViewHelper(); ?> 
                                    </div><!--/span-->
                                    <div class="span2">
                                        <label>Aula</label>
                                        <?php echo $this->formulario->aulas_id_aula->renderViewHelper(); ?> 
                                    </div><!--/span-->
                                    <div class="span1">
                                        <label>Puesto</label>
                                        <?php echo $this->formulario->puesto->renderViewHelper(); ?> 
                                    </div><!--/span-->
                                </div><!--/row-->   
                                <div class="row-fluid">
                                    <div class="span12">
                                        <label>Observaciones</label>
                                        <?php echo $this->formulario->obs->renderViewHelper(); ?>    
                                    </div><!--/span-->
                                </div><!--/row-->
                            </div>
                        </div>
                    </form>
                </div>
            </div><!--/span-->
        </div><!--/row-->
        <div class="row-fluid">		
            <div class="box span12">
                <div class="box-header" data-original-title>
                    <h2><i class="fa-icon-hdd"></i><span class="break"></span>Historial de averías y mantenimientos</h2>
                    <div class="box-icon">
                        <a href="#" id="toggle-fullscreen" class="hidden-phone hidden-tablet"><i class="halflings-icon fullscreen"></i></a>
                        <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                        <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                    </div>
                </div>
                <div class="box-content">
                    <table id="tabla" class="table table-striped table-bordered bootstrap-datatable datatable">
                        <thead>
                            <tr>
                                <th>Id Incidencia</th>
                                <th>Tipo</th>
                                <th>Fecha</th>
                                <th>Causa</th>
                                <th>Responsable</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>  
                        <tbody></tbody>
                        <tfoot>
                        </tfoot>
                    </table>            
                </div>
            </div><!--/span-->

        </div><!--/row-->
        <!-- end: Content -->
    </div><!--/#content.span11-->
</div><!--/fluid-row-->