<script type="text/javascript">
    var asInitVals = new Array();
    $(document).ready(function() {
        /*******************************************************************/
        /*Configuración datatables                                         */
        /*******************************************************************/
        $.extend($.fn.dataTableExt.oStdClasses, {
            "sWrapper": "dataTables_wrapper form-inline"
        });

        $.fn.dataTableExt.oApi.fnStandingRedraw = function(oSettings) {
            if (oSettings.oFeatures.bServerSide === false) {
                var before = oSettings._iDisplayStart;
                oSettings.oApi._fnReDraw(oSettings);
                // iDisplayStart has been reset to zero - so lets change it back
                oSettings._iDisplayStart = before;
                oSettings.oApi._fnCalculateEnd(oSettings);
            }
            // draw the 'current' page
            oSettings.oApi._fnDraw(oSettings);
        };
        /* API method to get paging information */
        $.fn.dataTableExt.oApi.fnPagingInfo = function(oSettings)
        {
            return {
                "iStart": oSettings._iDisplayStart,
                "iEnd": oSettings.fnDisplayEnd(),
                "iLength": oSettings._iDisplayLength,
                "iTotal": oSettings.fnRecordsTotal(),
                "iFilteredTotal": oSettings.fnRecordsDisplay(),
                "iPage": Math.ceil(oSettings._iDisplayStart / oSettings._iDisplayLength),
                "iTotalPages": Math.ceil(oSettings.fnRecordsDisplay() / oSettings._iDisplayLength)
            };
        }
        /* Bootstrap style pagination control */
        $.extend($.fn.dataTableExt.oPagination, {
            "bootstrap": {
                "fnInit": function(oSettings, nPaging, fnDraw) {
                    var oLang = oSettings.oLanguage.oPaginate;
                    var fnClickHandler = function(e) {
                        e.preventDefault();
                        if (oSettings.oApi._fnPageChange(oSettings, e.data.action)) {
                            fnDraw(oSettings);
                        }
                    };

                    $(nPaging).addClass('pagination').append(
                            '<ul>' +
                            '<li class="prev disabled"><a href="#">&larr; ' + oLang.sPrevious + '</a></li>' +
                            '<li class="next disabled"><a href="#">' + oLang.sNext + ' &rarr; </a></li>' +
                            '</ul>'
                            );
                    var els = $('a', nPaging);
                    $(els[0]).bind('click.DT', {action: "previous"}, fnClickHandler);
                    $(els[1]).bind('click.DT', {action: "next"}, fnClickHandler);
                },
                "fnUpdate": function(oSettings, fnDraw) {
                    var iListLength = 5;
                    var oPaging = oSettings.oInstance.fnPagingInfo();
                    var an = oSettings.aanFeatures.p;
                    var i, j, sClass, iStart, iEnd, iHalf = Math.floor(iListLength / 2);

                    if (oPaging.iTotalPages < iListLength) {
                        iStart = 1;
                        iEnd = oPaging.iTotalPages;
                    }
                    else if (oPaging.iPage <= iHalf) {
                        iStart = 1;
                        iEnd = iListLength;
                    } else if (oPaging.iPage >= (oPaging.iTotalPages - iHalf)) {
                        iStart = oPaging.iTotalPages - iListLength + 1;
                        iEnd = oPaging.iTotalPages;
                    } else {
                        iStart = oPaging.iPage - iHalf + 1;
                        iEnd = iStart + iListLength - 1;
                    }

                    for (i = 0, iLen = an.length; i < iLen; i++) {
                        // Remove the middle elements
                        $('li:gt(0)', an[i]).filter(':not(:last)').remove();

                        // Add the new list items and their event handlers
                        for (j = iStart; j <= iEnd; j++) {
                            sClass = (j == oPaging.iPage + 1) ? 'class="active"' : '';
                            $('<li ' + sClass + '><a href="#">' + j + '</a></li>')
                                    .insertBefore($('li:last', an[i])[0])
                                    .bind('click', function(e) {
                                        e.preventDefault();
                                        oSettings._iDisplayStart = (parseInt($('a', this).text(), 10) - 1) * oPaging.iLength;
                                        fnDraw(oSettings);
                                    });
                        }

                        // Add / remove disabled classes from the static elements
                        if (oPaging.iPage === 0) {
                            $('li:first', an[i]).addClass('disabled');
                        } else {
                            $('li:first', an[i]).removeClass('disabled');
                        }

                        if (oPaging.iPage === oPaging.iTotalPages - 1 || oPaging.iTotalPages === 0) {
                            $('li:last', an[i]).addClass('disabled');
                        } else {
                            $('li:last', an[i]).removeClass('disabled');
                        }
                    }
                }
            }
        });


        $.fn.dataTableExt.oApi.fnMultiFilter = function(oSettings, oData) {
            for (var key in oData)
            {
                if (oData.hasOwnProperty(key))
                {
                    for (var i = 0, iLen = oSettings.aoColumns.length; i < iLen; i++)
                    {
                        if (oSettings.aoColumns[i].sName == key)
                        {
                            /* Add single column filter */
                            oSettings.aoPreSearchCols[ i ].sSearch = oData[key];
                            break;
                        }
                    }
                }
            }
            this.oApi._fnReDraw(oSettings);
        };
        /******************************************************************/
        /* INICIALIZACIÓN DATATABLES: Configuración columnas y script php */
        /******************************************************************/
        oTable = $('#tabla').dataTable({
            //"sDom": "<'row-fluid'<'span6'T><'span6'f>r>t<'row-fluid'<'span6'i><'span6'>>S",
            //"sDom": "frtiS",
            "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span12'i><'span12 center'p>>",
            //"sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span12'iS><'span12 center'p>>",
            "sAjaxSource": "<?php echo $this->baseUrl("/php/permisos.php"); ?>",
            "bProcessing": true,
            "bServerSide": true,
            "bStateSave": true,
            "bAutoWidth": false,
            "bDeferRender": true,
            "sPaginationType": "bootstrap",
            "fnInitComplete": function() {
                var oSettings = $('#tabla').dataTable().fnSettings();
                for (var i = 0; i < oSettings.aoPreSearchCols.length; i++) {
                    if (oSettings.aoPreSearchCols[i].sSearch.length > 0) {
                        $("thead input, thead select")[i].value = oSettings.aoPreSearchCols[i].sSearch;
                        // $("tfoot input")[i].className = "";
                    }
                }
            },
            "aoColumns": [
                {
                    "mData": "perfil",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "perfil"
                },
                {
                    "mData": "nombre",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "nombre"
                },
                {
                    "mData": "descripcion",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "descripcion"
                },
                {
                    "mData": "regla_id",
                    "sClass": "valignCenter",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "mRender": function(data, type, full) {
                        if (data !== null)
                            return '<span class="label label-success">Permitido</span>';
                        return '<span class="label">Bloqueado</span>';
                    },
                    "sWidth": "100px"
                },
                {
                    "mData": "regla_id",
                    "sClass": "center",
                    "mRender": function(data, type, full) {
                        if (data !== null)
                            return '<a  title="Bloquear regla para el perfil de usuario" style="margin:3px;" class="btn btn-warning bloquearbtn" href="#"><i class="halflings-icon ban-circle halflings-icon"></i></a><a title="Permitir regla para el perfil de usuario" style="margin:3px; pointer-events: none;" disabled class="btn btn-success desbloquearbtn" href="#"><i class="halflings-icon ok halflings-icon"></i></a>';
                        return '<a  title="Bloquear regla para el perfil de usuario" disabled style="margin:3px; pointer-events: none;" class="btn btn-warning bloquearbtn" href="#"><i class="halflings-icon ban-circle halflings-icon"></i></a><a title="Permitir regla para el perfil de usuario" style="margin:3px;" class="btn btn-success desbloquearbtn" href="#"><i class="halflings-icon ok halflings-icon"></i></a>';
                    },
                    "bSortable": false,
                    "bSearchable": false,
                    "sWidth": "100px"

                },
                {
                    "mData": "acl_id",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false,
                    "sName": "acl_id"
                },
                {
                    "mData": "perfil_id",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false,
                    "sName": "perfil_id"
                }
            ],
            "aaSorting": [[1, "asc"]],
            //"aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
            "oLanguage": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros por página",
                "sZeroRecords": "No se encontraron resultados",
                "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                "sInfoFiltered": "(Filtrado de _MAX_ registros en total)",
                "sLoadingRecords": "Por favor espere - cargando...",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sPrevious": "Anterior",
                    "sNext": "Siguiente",
                    "sLast": "Último"
                }
            }
        });


        $(".sborrar").click(function() {
            $(this).prev().val("");
            $("thead input").keyup();
        });

        $("thead input, thead select").on("click keyup", function() {
            vsnombre = $("#snombre").val();
            vsperfil = $("#sperfil").val();
            vsdescripcion = $("#sdescripcion").val();
            /* Filter on the column (the index) of this element */

            //oTable.fnMultiFilter( { kk: this.value } );
            oTable.fnMultiFilter({"perfil": vsperfil, "nombre": vsnombre, "descripcion": vsdescripcion});
            //oTable.fnDraw();
            //oTable.fnMultiFilter( this.value, $("tfoot input").index(this) );
        });


        function removeClass(element)
        {
            var row = classTable.fnGetData(element);
            var id = row[0];
        }
        /*******************************************************************/
        /* EVENTOS DE LA PÁGINA                                            */
        /*******************************************************************/
        $.extend($.gritter.options, {
            /*class_name: 'gritter-light',*/
            position: 'bottom-right', // possibilities: bottom-left, bottom-right, top-left, top-right
            fade_in_speed: 100, // how fast notifications fade in (string or int)
            fade_out_speed: 100, // how fast the notices fade out
            time: 3000 // hang on the screen for...
        });

          $("#tabla").on('click', ".desbloquearbtn", function(e) {
            e.preventDefault();
            var nRow = $(this).parents('tr')[0];
            var aData = oTable.fnGetData(nRow);
            //insertaremos un registro (nueva regla_id) con los acl_id y perfil_id:
            //var regla_id = aData.regla_id;
            var acl_id = aData.acl_id;
            var perfil_id = aData.perfil_id;
            /*si el tipo hidden viene vacío el ajax no lo procesa, lo tenemos que extraer antes de la cadena*/
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: "<?php echo $this->baseUrl('/permisos/guardar/'); ?>",
                async: false,
                // you can use an object here
                data: {"acl_id": acl_id, "perfil_id": perfil_id},
                //includes the response status (e.g. 404 not found) and an error message
                error: function(xhr, status, error) {
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: '¡Error al guardar el registro!',
                        // (string | mandatory) the text inside the notification
                        text: 'No se ha podido cambiar el permiso',
                        image: '/img/block.png'
                    });

                },
                success: function(data) {
                    $("html").css('cursor', 'auto');
                    if (data["estado"]) {
                        var imagen = '/img/fail.png';
                        var texto = "Ha ocurrido un error al cambiar el permiso: <br/>" + data["respuesta"];
                    } else
                    {
                        var imagen = '/img/ok.png';
                        var texto = "Se ha modificado el permiso correctamente";
                    }
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: 'Permisos ',
                        // (string | mandatory) the text inside the notification
                        text: texto,
                        image: imagen

                    });
                    oTable.fnStandingRedraw();
                }
            });
        });
          $("#tabla").on('click', ".bloquearbtn", function(e) {
            e.preventDefault();
            var nRow = $(this).parents('tr')[0];
            var aData = oTable.fnGetData(nRow);
            //con obtener el id_regla para borrarlo es suficiente:
            var regla_id = aData.regla_id;
            //var acl_id = aData.acl_id;
            //var perfil_id = aData.regla_id;
            /*si el tipo hidden viene vacío el ajax no lo procesa, lo tenemos que extraer antes de la cadena*/
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: "<?php echo $this->baseUrl('/permisos/borrar/'); ?>",
                async: false,
                // you can use an object here
                data: {"regla_id": regla_id},
                //includes the response status (e.g. 404 not found) and an error message
                error: function(xhr, status, error) {
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: '¡Error al guardar el registro!',
                        // (string | mandatory) the text inside the notification
                        text: 'No se ha podido cambiar el permiso',
                        image: '/img/block.png'
                    });

                },
                success: function(data) {
                    $("html").css('cursor', 'auto');
                    if (data["estado"]) {
                        var imagen = '/img/fail.png';
                        var texto = "Ha ocurrido un error al cambiar el permiso: <br/>" + data["respuesta"];
                    } else
                    {
                        var imagen = '/img/ok.png';
                        var texto = "Se ha modificado el permiso correctamente";
                    }
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: 'Permisos ',
                        // (string | mandatory) the text inside the notification
                        text: texto,
                        image: imagen

                    });
                    oTable.fnStandingRedraw();
                }
            });
        });
        $("#mnuconf").addClass("active");
    }); /*Fin de document.ready*/
</script>
<div class="row-fluid">
<?php echo $this->partial('menu.php'); ?> 
    <noscript>
    <div class="alert alert-block span11">
        <h4 class="alert-heading">Aviso!</h4>
        <p>Necesitas <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> para poder visualizar correctamente esta página.</p>
    </div>
    </noscript>
    <!-- start: Content -->
    <div id="content" class="span11">

        <div style="float:right;" class="btn-toolbar">
            <div class="btn-group">
                <a class="btn" href="/departamentos"><i class="fa-icon-home"></i><span class="hidden-tablet"> Departamentos</span></a>
                <a class="btn" href="/usuarios"><i class="fa-icon-user"></i><span class="hidden-tablet"> Usuarios</span></a>
                <a class="btn" href="/aulas"><i class="fa-icon-sitemap"></i><span class="hidden-tablet"> Aulas</span></a>
                <a class="btn" href="/materiales"><i class="fa-icon-hdd"></i><span class="hidden-tablet"> Materiales</span></a>
                <a class="btn" href="/proveedores"><i class="fa-icon-shopping-cart"></i><span class="hidden-tablet"> Proveedores</span></a>
                <a class="btn active" href="/permisos"><i class="fa-icon-key"></i><span class="hidden-tablet"> Permisos</span></a>
            </div>
        </div>

        <div class="row-fluid">
            <h1>Permisos</h1>
        </div>
        <div class="row-fluid">		
            <div class="box span12">
                <div class="box-header" data-original-title>
                    <h2><i class="fa-icon-hdd"></i><span class="break"></span>Listado de Permisos</h2>
                    <div class="box-icon">
                        <a href="#" id="print-pdf" class="hidden-phone hidden-tablet"><i class="halflings-icon print"></i></a>
                        <a href="#" id="toggle-fullscreen" class="hidden-phone hidden-tablet"><i class="halflings-icon fullscreen"></i></a>
                        <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                        <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                    </div>
                </div>
                <div class="box-content">
                    <table id="tabla" class="table table-striped table-bordered bootstrap-datatable datatable">
                        <thead>
                            <tr>
                                <th>
                                    <select id="sperfil" class="search_init" >
                                        <option value="" selected>Filtrar perfil</option>
                                        <option value="Profesor">Profesor</option>
                                        <option value="Jefe de Departamento">Jefe de Departamento</option>
                                        <option value="Jefe de Estudios">Jefe de Estudios</option>
                                        <option value="Secretario">Secretario</option>
                                        <option value="Director">Director</option>
                                    </select>
                                </th>
                                <th>
                        <div class="input-append">
                            <input type="text" id="snombre" placeholder="Filtrar tipo" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div>
                        </th>
                        <th>
                        <div class="input-append">
                            <input type="text" id="sdescripcion" placeholder="Filtrar descripción" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div>
                        </th>
                        <th>

                        </th>
                        <th></th>
                        <th></th>
                        <th></th>
                        </tr>
                        <tr>
                            <th title="Perfil del usuario">Perfil</th>
                            <th title="Nombre descriptivo tipo de regla">Tipo de Regla</th>
                            <th title="Descripción de una regla y dependencias con otras.">Descripción</th>
                            <th title="Estado del permiso actual de una regla para un perfil de usuario">Estado</th>
                            <th title="Permitir o bloquear una regla para un perfil de usuario">Acciones</th>
                            <th>Id ACL</th>
                            <th>Id perfil</th>
                        </tr>

                        </thead>  
                        <tbody></tbody>
                        <tfoot>

                        </tfoot>
                    </table>            
                </div>
            </div><!--/span-->

        </div><!--/row-->
    </div><!--/#content.span11-->
</div><!--/fluid-row-->
