<div class="row-fluid">
    <?php echo $this->partial('menu.php'); ?> 
    <noscript>
    <div class="alert alert-block span11">
        <h4 class="alert-heading">Aviso!</h4>
        <p>Necesitas <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> para poder visualizar correctamente esta página.</p>
    </div>
    </noscript>

    <!-- start: Content -->
    <!-- start: Content -->
    <div id="content" class="span11">
        <div class="row-fluid">
            <h1>Acceso no permitido</h1>
            
            <p>Tu perfil de usuario no tiene acceso a esta funcionalidad de la aplicación.</p>
            <img style="width:300px" src="/img/accessdenied.jpg">
        </div>
    </div><!--/#content.span11-->
</div><!--/fluid-row-->









