<script type="text/javascript">
    $(document).ready(function() {

        /*******************************************************************/
        /* Validación formulario                                           */
        /*******************************************************************/
        var formvalidator = $("#formulario").validate({
            /*bug hacía el validate con la fecha "antigua", antes de la selección*/

            rules: {
                causa: {
                    required: true
                },
                fecha_mantenimiento: {
                    required: true
                },
                responsable: {
                    required: true
                }
            },
            messages: {
                causa: {
                    required: "Debes rellenar la causa del mantenimiento"
                },
                fecha_mantenimiento: {
                    required: "Debes rellenar la fecha de asignación del mantenimiento"
                },
                responsable: {
                    required: "Debes rellenar el responsable del mantenimiento"
                }
            }
        });

        $.extend($.gritter.options, {
            /*class_name: 'gritter-light',*/
            position: 'bottom-right', // possibilities: bottom-left, bottom-right, top-left, top-right
            fade_in_speed: 100, // how fast notifications fade in (string or int)
            fade_out_speed: 100, // how fast the notices fade out
            time: 3000 // hang on the screen for...
        });

        $("#cancelar").click(function() {
            window.location.href = "<?php echo $this->baseUrl('/mantenimientos/'); ?>";
        });



        $("#guardar").click(function(e) {
            e.preventDefault();
            $("html").css('cursor', 'wait');
            resultado = $("#formulario").validate().form();
            if (!resultado) {
                $("html").css('cursor', 'auto');
                return;
            }
            var datos = $("#formulario").serialize();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: "<?php echo $this->baseUrl('/mantenimientos/guardar/'); ?>",
                async: false,
                // you can use an object here
                data: datos,
                //includes the response status (e.g. 404 not found) and an error message
                error: function(xhr, status, error) {
                    alert (xhr);
                    alert (status);
                    alert (error);
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: '¡Error al guardar el registro!',
                        // (string | mandatory) the text inside the notification
                        text: 'No se ha guardado el Mantenimiento',
                        image: '/img/block.png'
                    });

                },
                success: function(data) {
                    $("html").css('cursor', 'auto');
                    if (data["estado"]) {
                        var imagen = '/img/fail.png';
                        var texto = "Ha ocurrido un error en la inserción en la bbdd: <br/>" + data["respuesta"];
                        $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: 'Alta Mantenimiento ',
                            // (string | mandatory) the text inside the notification
                            text: texto,
                            image: imagen

                        });
                        
                    }
                    else
                    {
                        window.location.href = '<?php echo $this->baseUrl('/mantenimientos/index/insertada/ok'); ?>';
                    }

                },
                complete: {
                }
            });
        });

        $('#fecha_mantenimiento').mouseenter(function() {
            $('#fecha_mantenimiento').datepicker({
                format: 'dd-mm-yyyy',
                weekStart: 1,
                language: "es",
                todayHighlight: true,
                autoclose: true
            });
        });
        $('#fecha_mantenimiento').change(function() {
            $('#fecha_mantenimiento').datepicker('remove');
        });

        $('#fecha_solucion').mouseenter(function() {
            $('#fecha_solucion').datepicker({
                format: 'dd-mm-yyyy',
                weekStart: 1,
                language: "es",
                todayHighlight: true,
                autoclose: true
            });
        });
        $('#fecha_solucion').change(function() {
            $('#fecha_solucion').datepicker('remove');
        });



        $('#responsable').focus(function() {
            if (!$("#responsable").val()) {
                $.gritter.add({
                    // (string | mandatory) the heading of the notification
                    title: 'Responsables del aula',
                    // (string | mandatory) the text inside the notification
                    text: 'Falta configurar los responsables del aula ',
                    image: '/img/block.png'
                });
            }
        });
        /*Controlamos los usuarios a los que se asignan los mantenimientos*/
        $("#aulas_id_aula").change(function() {
            var id_aula = $("#aulas_id_aula").val();
            $("#responsable").find('option').remove().end();
            /*ponemos como responsable al jefe de departamento*/
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: "<?php echo $this->baseUrl('/aulas/getresponsables/'); ?>",
                async: false,
                // you can use an object here
                data: {'id_aula': id_aula},
                //includes the response status (e.g. 404 not found) and an error message
                error: function(xhr, status, error) {
                    if (xhr.status === 401) {
                        location.href = "<?php echo $this->baseUrl('/usuarios/login/'); ?>";
                    }
                    alert(xhr.status);
                    alert(status);
                    alert(error);
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: 'Responsables del aula',
                        // (string | mandatory) the text inside the notification
                        text: 'No se han podido obtener los responsables del aula ',
                        image: '/img/block.png'
                    });

                },
                success: function(data) {
                    $("html").css('cursor', 'auto');
                    if (data["estado"]) {
                        var imagen = '/img/fail.png';
                        var texto = "Ha ocurrido un error en la consulta a la bbdd: <br/>" + data["respuesta"];
                    }
                    else {
                        /*rellenamos el combo con los profesores del departamento:*/
                        var datos = false;
                        $.each(data, function(val, text) {
                            $("#responsable").append(
                                    $('<option></option>').val(val).html(text)
                                    );
                            datos = true;
                        });
                        /* if (!datos) {
                         
                         $.gritter.add({
                         // (string | mandatory) the heading of the notification
                         title: 'Responsables del aula',
                         // (string | mandatory) the text inside the notification
                         text: 'Falta configurar los reponsables del aula',
                         image: '/img/block.png'
                         });
                         
                         
                         }*/
                    }
                },
                complete: {
                }
            });

        });

        /*Lo ejecutamos al menos una vez:*/
        $("#aulas_id_aula").change();
    }); /*Fin de document.ready*/
</script>
<div class="row-fluid">
    <?php echo $this->partial('menu.php'); ?> 
    <noscript>
    <div class="alert alert-block span11">
        <h4 class="alert-heading">Aviso!</h4>
        <p>Necesitas <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> para poder visualizar correctamente esta página.</p>
    </div>
    </noscript>

    <!-- start: Content -->
    <div id="content" class="span11">
        <div class="row-fluid">
            <h1>Mantenimientos</h1>
            <div id="herramientas"></div>
        </div>
        <div id="divadd" class="row-fluid">
            <div class="box span12">
                <div class="box-header" data-original-title>
                    <h2 id="titulo"><i class="halflings-icon edit"></i><span class="break"></span>Editar Mantenimiento</h2>
                    <div class="box-icon">
                        <a href="#" id="toggle-fullscreen" class="hidden-phone hidden-tablet"><i class="halflings-icon fullscreen"></i></a>
                        <a href="#" id="minnuevo" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                        <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                    </div>
                </div>
                <div class="box-content">

                    <form  method="<?php echo $this->formulario->getMethod() ?>" action="<?php echo $this->formulario->getAction() ?>" name="<?php echo $this->formulario->getName() ?>" id="<?php echo $this->formulario->getName() ?>">
                        <div class="row-fluid">
                            <div class="span12">   
                                <div class="row-fluid">  
                                    <div class="span2">
                                        <label>Fecha asignación</label>
                                        <?php echo $this->formulario->id_mantenimiento->renderViewHelper(); ?>  
                                        <?php echo $this->formulario->detectadapor->renderViewHelper(); ?>  
                                        <?php echo $this->formulario->fecha_mantenimiento->renderViewHelper(); ?>
                                    </div><!--/span-->
                                    <div class="span4">
                                        <label>Aula</label>
                                        <?php echo $this->formulario->aulas_id_aula->renderViewHelper(); ?>  
                                    </div><!--/span-->
                                    <div class="span4">
                                        <label>Responsable</label>
                                        <?php echo $this->formulario->responsable->renderViewHelper(); ?>                                
                                    </div><!--/span-->

                                    <div class="span2">
                                        <label>Fecha realización</label>
                                        <?php echo $this->formulario->fecha_solucion->renderViewHelper(); ?>
                                    </div><!--/span-->
                                </div>
                                <div class="row-fluid">
                                    <div class="span2">
                                        <label>Prioridad</label>
                                        <?php echo $this->formulario->prioridad->renderViewHelper(); ?>
                                    </div><!--/row-->
                                    <div class="span10">
                                        <label>Causa</label>
                                        <?php echo $this->formulario->causa->renderViewHelper(); ?>    
                                    </div><!--/span-->
                                </div><!--/row-->
                                <div class="row-fluid">
                                    <div class="span12">
                                        <label>Descripción</label>
                                        <?php echo $this->formulario->descripcion->renderViewHelper(); ?>    
                                    </div><!--/span-->
                                </div><!--/row-->
                                <div class="form-actions">               
                                    <?php echo $this->formulario->guardar->renderViewHelper(); ?> 
                                    <?php echo $this->formulario->cancelar->renderViewHelper(); ?> 
                                </div><!--/form-actions-->
                            </div>
                        </div>
                    </form>
                </div>
            </div><!--/span-->
        </div><!--/row-->
    </div><!--/#content.span11-->
    <!-- Formulario de borrado -->
    <div class="modal hide" id="deleteModal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Borrar Mantenimiento</h3>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Cancelar</a>
            <a id="borrar" href="#" class="btn btn-primary">Borrar</a>
        </div>
    </div>
</div><!--/fluid-row-->