<script type="text/javascript">
    $(document).ready(function() {
        /*******************************************************************/
        /*Configuración datatables                                         */
        /*******************************************************************/
        $.extend($.fn.dataTableExt.oStdClasses, {
            "sWrapper": "dataTables_wrapper form-inline"
        });

        $.fn.dataTableExt.oApi.fnStandingRedraw = function(oSettings) {
            if (oSettings.oFeatures.bServerSide === false) {
                var before = oSettings._iDisplayStart;
                oSettings.oApi._fnReDraw(oSettings);
                // iDisplayStart has been reset to zero - so lets change it back
                oSettings._iDisplayStart = before;
                oSettings.oApi._fnCalculateEnd(oSettings);
            }
            // draw the 'current' page
            oSettings.oApi._fnDraw(oSettings);
        };
        /* API method to get paging information */
        $.fn.dataTableExt.oApi.fnPagingInfo = function(oSettings)
        {
            return {
                "iStart": oSettings._iDisplayStart,
                "iEnd": oSettings.fnDisplayEnd(),
                "iLength": oSettings._iDisplayLength,
                "iTotal": oSettings.fnRecordsTotal(),
                "iFilteredTotal": oSettings.fnRecordsDisplay(),
                "iPage": Math.ceil(oSettings._iDisplayStart / oSettings._iDisplayLength),
                "iTotalPages": Math.ceil(oSettings.fnRecordsDisplay() / oSettings._iDisplayLength)
            };
        }
        /* Bootstrap style pagination control */
        $.extend($.fn.dataTableExt.oPagination, {
            "bootstrap": {
                "fnInit": function(oSettings, nPaging, fnDraw) {
                    var oLang = oSettings.oLanguage.oPaginate;
                    var fnClickHandler = function(e) {
                        e.preventDefault();
                        if (oSettings.oApi._fnPageChange(oSettings, e.data.action)) {
                            fnDraw(oSettings);
                        }
                    };

                    $(nPaging).addClass('pagination').append(
                            '<ul>' +
                            '<li class="prev disabled"><a href="#">&larr; ' + oLang.sPrevious + '</a></li>' +
                            '<li class="next disabled"><a href="#">' + oLang.sNext + ' &rarr; </a></li>' +
                            '</ul>'
                            );
                    var els = $('a', nPaging);
                    $(els[0]).bind('click.DT', {action: "previous"}, fnClickHandler);
                    $(els[1]).bind('click.DT', {action: "next"}, fnClickHandler);
                },
                "fnUpdate": function(oSettings, fnDraw) {
                    var iListLength = 5;
                    var oPaging = oSettings.oInstance.fnPagingInfo();
                    var an = oSettings.aanFeatures.p;
                    var i, j, sClass, iStart, iEnd, iHalf = Math.floor(iListLength / 2);

                    if (oPaging.iTotalPages < iListLength) {
                        iStart = 1;
                        iEnd = oPaging.iTotalPages;
                    }
                    else if (oPaging.iPage <= iHalf) {
                        iStart = 1;
                        iEnd = iListLength;
                    } else if (oPaging.iPage >= (oPaging.iTotalPages - iHalf)) {
                        iStart = oPaging.iTotalPages - iListLength + 1;
                        iEnd = oPaging.iTotalPages;
                    } else {
                        iStart = oPaging.iPage - iHalf + 1;
                        iEnd = iStart + iListLength - 1;
                    }

                    for (i = 0, iLen = an.length; i < iLen; i++) {
                        // Remove the middle elements
                        $('li:gt(0)', an[i]).filter(':not(:last)').remove();

                        // Add the new list items and their event handlers
                        for (j = iStart; j <= iEnd; j++) {
                            sClass = (j == oPaging.iPage + 1) ? 'class="active"' : '';
                            $('<li ' + sClass + '><a href="#">' + j + '</a></li>')
                                    .insertBefore($('li:last', an[i])[0])
                                    .bind('click', function(e) {
                                        e.preventDefault();
                                        oSettings._iDisplayStart = (parseInt($('a', this).text(), 10) - 1) * oPaging.iLength;
                                        fnDraw(oSettings);
                                    });
                        }

                        // Add / remove disabled classes from the static elements
                        if (oPaging.iPage === 0) {
                            $('li:first', an[i]).addClass('disabled');
                        } else {
                            $('li:first', an[i]).removeClass('disabled');
                        }

                        if (oPaging.iPage === oPaging.iTotalPages - 1 || oPaging.iTotalPages === 0) {
                            $('li:last', an[i]).addClass('disabled');
                        } else {
                            $('li:last', an[i]).removeClass('disabled');
                        }
                    }
                }
            }
        });


        $.fn.dataTableExt.oApi.fnMultiFilter = function(oSettings, oData) {
            for (var key in oData)
            {
                if (oData.hasOwnProperty(key))
                {
                    for (var i = 0, iLen = oSettings.aoColumns.length; i < iLen; i++)
                    {
                        if (oSettings.aoColumns[i].sName == key)
                        {
                            /* Add single column filter */
                            oSettings.aoPreSearchCols[ i ].sSearch = oData[key];
                            break;
                        }
                    }
                }
            }
            this.oApi._fnReDraw(oSettings);
        };


        /******************************************************************/
        /* INICIALIZACIÓN DATATABLES: Configuración columnas y script php */
        /******************************************************************/
        oTable = $('#tabla').dataTable({
            //"sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span12'i><'span12 center'p>>",
            /*"<'row-fluid'<'span6'T><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",*/
            "fnServerParams": function(aoData) {
                aoData.push({"name": "id_departamento", "value": id_departamento});
            },
            "sAjaxSource": "<?php echo $this->baseUrl("/php/incidenciasfungibles.php"); ?>",
            "bProcessing": true,
            "bServerSide": true,
            "bStateSave": true,
            "bAutoWidth": false,
            "sScrollX": "100%",
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "fnInitComplete": function() {
                var oSettings = $('#tabla').dataTable().fnSettings();
                for (var i = 0; i < oSettings.aoPreSearchCols.length; i++) {
                    if (oSettings.aoPreSearchCols[i].sSearch.length > 0) {
                        $("thead input, thead select")[i].value = oSettings.aoPreSearchCols[i].sSearch;
                        // $("tfoot input")[i].className = "";
                    }
                }
            },
            "aoColumns": [
                {
                    "mData": "fecha_incidencia",
                    "bSearchable": true,
                    "mRender": function(data, type, full) {
                        return fecha_ddmmyyyy(data);
                    },
                    "bVisible": true,
                    "bSortable": true,
                    "sWidth": "80px",
                    "sName": "fecha_incidencia"
                },
                {
                    "mData": "aula",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sWidth": "60px",
                    "sName": "aula"
                },
                {
                    "mData": "estado",
                    "mRender": function(data, type, full) {
                        if (data === "Cerrada")
                            return "<span class='label'>Cerrada</span>";
                        else if (data === "Abierta en Centro")
                            return "<span class='label label-important'>Abierta en Centro</span>";
                        else
                            return "<span class='label label-inverse'>Abierta en Proveedor</span>";
                    },
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sWidth": "60px",
                    "sName": "estado"

                },
                {
                    "mData": "causa",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "causa"
                },
                {
                    "mData": "prioridad",
                    "mRender": function(data, type, full) {
                        if (data === "Alta")
                            return "<span class='label label-important'>Alta</span>";
                        else if (data === "Media")
                            return "<span class='label label-warning'>Media</span>";
                        else
                            return "<span class='label label-success'>Baja</span>";
                    },
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sWidth": "90px",
                    "sName": "prioridad"
                },
                {
                    "mData": "nombrecompleto",
                    "bSearchable": true,
                    "bVisible": true,
                    "bSortable": true,
                    "sName": "nombrecompleto"
                },
                {
                    "mData": "id_incidencia",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                },
                {
                    "mData": "responsable",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                },
                {
                    "mData": "departamento",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                },
                {
                    "mData": "descripcion",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                },
                {
                    "mData": "fecha_solucion",
                    "bSearchable": false,
                    "bVisible": false,
                    "bSortable": false
                },
                {
                    "mData": "id_incidencia",
                    "sClass": "center accion",
                    "mRender": function(data, type, full) {
                        return '<a title="Editar incidencia" style="margin:3px;" title="Editar incidencia" class="btn btn-info editarbtn" href="<?php echo $this->baseUrl('/incidenciasfungibles/editardet/id_incidencia/'); ?>' + data + '"><i class="halflings-icon edit halflings-icon"></i></a><a title="Eliminar incidencia" data-toggle="modal" href="#deleteModal" style="margin:3px;" class="btn btn-danger borrarbtn"><i class="halflings-icon trash halflings-icon"></i></a>';
                    },
                    "bSortable": false,
                    "bSearchable": false,
                    "sWidth": "100px"
                }
            ],
            "aaSorting": [[0, "desc"]],
            "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
            "oLanguage": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros por página",
                "sZeroRecords": "No se encontraron resultados",
                "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                "sInfoFiltered": "(Filtrado de _MAX_ registros en total)",
                "sLoadingRecords": "Por favor espere - cargando...",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sPrevious": "Anterior",
                    "sNext": "Siguiente",
                    "sLast": "Último"
                }
            },
            "fnDrawCallback": function() {
                $('#tabla tbody td:not(.accion)').click(edicion);

                $('#tabla tbody tr').hover(function() {
                    $(this).css('cursor', 'pointer');
                }, function() {
                    $(this).css('cursor', 'auto');
                });
            }
        });
        $(".sborrar").click(function() {
            $(this).prev().val("");
            $("thead input").keyup();
        });

        function edicion(e) {
            e.preventDefault();
            var nRow = $(this).parents('tr')[0];
            var aData = oTable.fnGetData(nRow);
            window.location.href = '<?php echo $this->baseUrl('/incidenciasfungibles/editardet/id_incidencia/'); ?>' + aData.id_incidencia;
        }



        $("thead input, thead select").on("click keyup", function() {
            vsfecha_incidencia = $("#sfecha_incidencia").val();
            vsaula = $("#saula").val();
            vsestado = $("#sestado").val();
            vscausa = $("#scausa").val();
            vsprioridad = $("#sprioridad").val();
            vsnombrecompleto = $("#snombrecompleto").val();

            /* Filter on the column (the index) of this element */

            //oTable.fnMultiFilter( { kk: this.value } );
            oTable.fnMultiFilter({"fecha_incidencia": vsfecha_incidencia, "aula": vsaula,  "estado": vsestado, "causa": vscausa, "prioridad": vsprioridad, "nombrecompleto": vsnombrecompleto});
            //oTable.fnDraw();
            //oTable.fnMultiFilter( this.value, $("tfoot input").index(this) );
        });


        function removeClass(element)
        {
            var row = classTable.fnGetData(element);
            var id = row[0];
        }

        /********************************************************************/
        /*Table Tools Configuración botón añadir concepto   A RELLENAR       */
        /********************************************************************/
        TableTools.BUTTONS.boton = $.extend(true, TableTools.buttonBase, {
            "sNewLine": "<br>",
            "sButtonText": "Copy to element",
            "sDiv": ""
        });
        /*******************************************************************/
        /*Configuración TableTools                                         */
        /*******************************************************************/
        var oTableTools = new TableTools(oTable, {
            "sSwfPath": "/js/swf/copy_csv_xls_pdf.swf",
            "aButtons": [
                {
                    "sExtends": "boton",
                    "sButtonText": "Listado",
                    "fnClick": function(nButton, oConfig) {
                        window.location.href = '<?php echo $this->baseUrl("/incidenciasfungibles/"); ?>';
                    }
                },
                {
                    "sExtends": "boton",
                    "sButtonText": "Nueva",
                    "fnClick": function(nButton, oConfig) {
                        window.location.href = '<?php echo $this->baseUrl("/incidenciasfungibles/editar/"); ?>';
                    }
                },
                {
                    "sExtends": "xls",
                    "sButtonText": "Excel",
                    "mColumns": "sortable",
                    "sFileName": "listado_incidencias_fungibles.xls"
                }

            ]
        });
        $('#herramientas').before(oTableTools.dom.container);
        // Set the classes that TableTools uses to something suitable for Bootstrap
        $.extend(true, $.fn.DataTable.TableTools.classes, {
            "container": "btn-group",
            "buttons": {
                "normal": "btn",
                "disabled": "btn disabled"
            },
            "collection": {
                "container": "DTTT_dropdown dropdown-menu",
                "buttons": {
                    "normal": "",
                    "disabled": "disabled"
                }
            }
        });

        // Have the collection use a bootstrap compatible dropdown
        $.extend(true, $.fn.DataTable.TableTools.DEFAULTS.oTags, {
            "collection": {
                "container": "ul",
                "button": "li",
                "liner": "a"
            }
        });



        /*******************************************************************/
        /* EVENTOS DE LA PÁGINA                                            */
        /*******************************************************************/
        $.extend($.gritter.options, {
            /*class_name: 'gritter-light',*/
            position: 'bottom-right', // possibilities: bottom-left, bottom-right, top-left, top-right
            fade_in_speed: 100, // how fast notifications fade in (string or int)
            fade_out_speed: 100, // how fast the notices fade out
            time: 3000 // hang on the screen for...
        });



        /*Borrado*/
        $("#tabla").on('click', ".borrarbtn", function(e) {
            e.preventDefault();
            var nRow = $(this).parents('tr')[0];
            var aData = oTable.fnGetData(nRow);
            /*var jqTds = $('>td', nRow);*/
            id_incidencia = aData.id_incidencia;
            $(".modal-body").html("<p> ¿Seguro que quieres borrar esta incidencia?</p>");
        });

        $("#borrar").click(function() {
            $("html").css('cursor', 'wait');
            $('#deleteModal').modal('hide');
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: "<?php echo $this->baseUrl() . '/incidenciasfungibles/borrar' ?>",
                async: false,
                // you can use an object here
                data: {id_incidencia: id_incidencia},
                //includes the response status (e.g. 404 not found) and an error message
                error: function(xhr, status, error) {
                    $("html").css('cursor', 'auto');
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: '¡Error al borrar el registro!',
                        // (string | mandatory) the text inside the notification
                        text: 'No se ha eliminado la Incidencia',
                        image: '/img/block.png'
                    });
                },
                success: function(data) {
                    $("html").css('cursor', 'auto');
                    if (data["estado"]) {
                        var imagen = '/img/fail.png';
                        var texto = "Ha ocurrido un error en la eliminación de la bbdd: <br/>" + data["respuesta"];
                    }
                    else
                    {
                        var imagen = '/img/ok.png';
                        var texto = 'Se ha eliminado la Incidencia';
                    }
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: 'Incidencias ',
                        // (string | mandatory) the text inside the notification
                        text: texto,
                        image: imagen

                    });
                    oTable.fnStandingRedraw();
                }

            });
        });


<?php if ($this->mostrar_mensaje) { ?>
            var imagen = '/img/ok.png';
            $.gritter.add({
                // (string | mandatory) the heading of the notification
                title: 'Incidencias',
                // (string | mandatory) the text inside the notification
                text: "Se ha procesado la incidencia",
                image: imagen

            });
            $("#mnuincidencias").addClass("active");
<?php } ?>

    }); /*Fin de document.ready*/
</script>

<div class="row-fluid">
    <?php echo $this->partial('menu.php'); ?> 
    <noscript>
    <div class="alert alert-block span11">
        <h4 class="alert-heading">Aviso!</h4>
        <p>Necesitas <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> para poder visualizar correctamente esta página.</p>
    </div>
    </noscript>

    <!-- start: Content -->
    <!-- start: Content -->
    <div id="content" class="span11">
        <div class="row-fluid">
            <h1>Incidencias material fungible</h1>
            <div id="herramientas" ></div>
        </div>

        <div class="row-fluid">		
            <div class="box span12">
                <div class="box-header" data-original-title>
                    <h2><i class="fa-icon-hdd"></i><span class="break"></span>Listado de Incidencias</h2>
                    <div class="box-icon">
                        <a href="#" id="toggle-fullscreen" class="hidden-phone hidden-tablet"><i class="halflings-icon fullscreen"></i></a>
                        <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                        <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                    </div>
                </div>
                <div class="box-content">

                    <table id="tabla" class="table table-striped table-bordered bootstrap-datatable datatable">
                        <thead>
                            <tr>
                                <th>                        
                        <div class="input-append" style="display:none">
                            <input type="text" id="sfecha_incidencia"  placeholder="Filtrar fecha" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div>
                        </th>
                        <th>
                        <div class="input-append">
                            <input type="text" id="saula"  placeholder="Filtrar aula" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div>

                        </th>
                        <th>
                            <select id="sestado"   class="search_init" >
                                <option value="" selected>Filtrar estado</option>
                                <option value="Abierta en Centro">Abierta en Centro</option>
                                <option value="Abierta en Proveedor">Abierta en Proveedor</option>
                                <option value="Cerrada">Cerrada</option>
                            </select>
                        </th>
                        <th>                        
                        <div class="input-append">
                            <input type="text" id="scausa"  placeholder="Filtrar causa" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div>
                        </th>
                        <th>
                            <select id="sprioridad"   class="search_init" >
                                <option value="" selected>Filtrar prioridad</option>
                                <option value="Media">Media</option>
                                <option value="Baja">Baja</option>
                                <option value="Alta">Alta</option>
                            </select>

                        </th>
                        <th><div class="input-append">
                            <input type="text" id="snombrecompleto"  placeholder="Filtrar responsable" class="search_init" />
                            <span class="sborrar add-on"><i class="icon-remove"></i></span>
                        </div></th>     
                        <th><!--Id Incidencia--></th>
                        <th><!--Id Reponsable--></th>
                        <th><!--Departamento--></th>
                        <th><!--Descripción--></th>
                        <th><!--Fecha Solución--></th>
                        <th title="Modificar o eliminar incidencias"><!--Acciones--></th>
                        </tr>
                        <tr>
                            <th title="Fecha de alta de la incidencia">Fecha</th>
                            <th title="Lugar de la incidencia">Aula</th>
                            <th title="Estado del material">Estado</th>
                            <th title="Causa de la incidencia">Causa</th>
                            <th title="Prioridad de la incidencia">Prioridad</th>
                            <th title="Persona asignada para resolver la incidencia">Responsable</th>     
                            <th>Id Incidencia</th>
                            <th>Id Reponsable</th>
                            <th>Departamento</th>
                            <th>Descripción</th>
                            <th>Fecha Solución</th>
                            <th>Acciones</th>
                        </tr>
                        </thead>  
                        <tbody></tbody>
                        <tfoot>
                        </tfoot>
                    </table>            
                </div>
            </div><!--/span-->

        </div><!--/row-->
        <!-- Formulario de borrado -->
        <div class="modal hide" id="deleteModal">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3>Borrar Incidencia</h3>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal">Cancelar</a>
                <a id="borrar" href="#" class="btn btn-primary">Borrar</a>
            </div>
        </div>
        <!-- end: Content -->
    </div><!--/#content.span11-->
</div><!--/fluid-row-->